# coding: utf-8

"""
    Service Inventory Management

    The intent of this API is to provide a consistent/standardized mechanism to query and manipulate the Service inventory. The Service Inventory API can be used to query the service instances for a customer via Self Service Portal or the Call Centre operator can query the service instances on behalf of the customer while a customer may have a complaint or a query. Note: Only the CustomerFacingServices instances will be presented to the customer. The Service Inventory API can be called by the Service Order Management to create a new service instance/ update an existing service instance in the Service Inventory. ### Service resource Service is an abstract base class for defining the Service hierarchy. All Services are characterized as either being possibly visible and usable by a Customer or not. This gives rise to the two subclasses of  Service: CustomerFacingService and ResourceFacingService. ### Service Inventory API performs the following operations on service  : - Retrieve  a service or a collection of services depending on filter criteria - Partial update of a service (including updating rules) - Create a service (including default values and creation rules and for administration users only) - Delete a service (for administration users only) - Notification of events on service

    The version of the OpenAPI document: 5.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from importlib import import_module
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from openapi_server.models.characteristic_relationship_fvo import CharacteristicRelationshipFVO
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class CharacteristicFVO(BaseModel):
    """
    CharacteristicFVO
    """ # noqa: E501
    type: StrictStr = Field(description="When sub-classing, this defines the sub-class Extensible name", alias="@type")
    base_type: Optional[StrictStr] = Field(default=None, description="When sub-classing, this defines the super-class", alias="@baseType")
    schema_location: Optional[StrictStr] = Field(default=None, description="A URI to a JSON-Schema file that defines additional attributes and relationships", alias="@schemaLocation")
    id: Optional[StrictStr] = Field(default=None, description="Unique identifier of the characteristic")
    name: StrictStr = Field(description="Name of the characteristic")
    value_type: Optional[StrictStr] = Field(default=None, description="Data type of the value of the characteristic", alias="valueType")
    characteristic_relationship: Optional[List[CharacteristicRelationshipFVO]] = Field(default=None, alias="characteristicRelationship")
    __properties: ClassVar[List[str]] = ["@type", "@baseType", "@schemaLocation", "id", "name", "valueType", "characteristicRelationship"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    # JSON field name that stores the object type
    __discriminator_property_name: ClassVar[List[str]] = '@type'

    # discriminator mappings
    __discriminator_value_class_map: ClassVar[Dict[str, str]] = {
        'BooleanArrayCharacteristic': 'BooleanArrayCharacteristicFVO','BooleanCharacteristic': 'BooleanCharacteristicFVO','Characteristic': 'CharacteristicFVO','IntegerArrayCharacteristic': 'IntegerArrayCharacteristicFVO','IntegerCharacteristic': 'IntegerCharacteristicFVO','NumberArrayCharacteristic': 'NumberArrayCharacteristicFVO','NumberCharacteristic': 'NumberCharacteristicFVO','ObjectArrayCharacteristic': 'ObjectArrayCharacteristicFVO','ObjectCharacteristic': 'ObjectCharacteristicFVO','StringArrayCharacteristic': 'StringArrayCharacteristicFVO','StringCharacteristic': 'StringCharacteristicFVO'
    }

    @classmethod
    def get_discriminator_value(cls, obj: Dict) -> str:
        """Returns the discriminator value (object type) of the data"""
        discriminator_value = obj[cls.__discriminator_property_name]
        if discriminator_value:
            return cls.__discriminator_value_class_map.get(discriminator_value)
        else:
            return None

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Union[Self, Self, Self, Self, Self, Self, Self, Self, Self, Self]:
        """Create an instance of CharacteristicFVO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in characteristic_relationship (list)
        _items = []
        if self.characteristic_relationship:
            for _item in self.characteristic_relationship:
                if _item:
                    _items.append(_item.to_dict())
            _dict['characteristicRelationship'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Union[Self, Self, Self, Self, Self, Self, Self, Self, Self, Self]:
        """Create an instance of CharacteristicFVO from a dict"""
        # look up the object type based on discriminator mapping
        object_type = cls.get_discriminator_value(obj)
        if object_type:
            klass = globals()[object_type]
            return klass.from_dict(obj)
        else:
            raise ValueError("CharacteristicFVO failed to lookup discriminator value from " +
                             json.dumps(obj) + ". Discriminator property name: " + cls.__discriminator_property_name +
                             ", mapping: " + json.dumps(cls.__discriminator_value_class_map))


