# coding: utf-8

"""
    Service Inventory Management

    The intent of this API is to provide a consistent/standardized mechanism to query and manipulate the Service inventory. The Service Inventory API can be used to query the service instances for a customer via Self Service Portal or the Call Centre operator can query the service instances on behalf of the customer while a customer may have a complaint or a query. Note: Only the CustomerFacingServices instances will be presented to the customer. The Service Inventory API can be called by the Service Order Management to create a new service instance/ update an existing service instance in the Service Inventory. ### Service resource Service is an abstract base class for defining the Service hierarchy. All Services are characterized as either being possibly visible and usable by a Customer or not. This gives rise to the two subclasses of  Service: CustomerFacingService and ResourceFacingService. ### Service Inventory API performs the following operations on service  : - Retrieve  a service or a collection of services depending on filter criteria - Partial update of a service (including updating rules) - Create a service (including default values and creation rules and for administration users only) - Delete a service (for administration users only) - Notification of events on service

    The version of the OpenAPI document: 5.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.characteristic import Characteristic
from openapi_server.models.entity_ref import EntityRef
from openapi_server.models.related_party_ref_or_party_role_ref import RelatedPartyRefOrPartyRoleRef
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class Event(BaseModel):
    """
    Event
    """ # noqa: E501
    type: StrictStr = Field(description="When sub-classing, this defines the sub-class Extensible name", alias="@type")
    base_type: Optional[StrictStr] = Field(default=None, description="When sub-classing, this defines the super-class", alias="@baseType")
    schema_location: Optional[StrictStr] = Field(default=None, description="A URI to a JSON-Schema file that defines additional attributes and relationships", alias="@schemaLocation")
    href: Optional[StrictStr] = Field(default=None, description="Hyperlink reference")
    id: Optional[StrictStr] = Field(default=None, description="unique identifier")
    correlation_id: Optional[StrictStr] = Field(default=None, description="The correlation id for this event.", alias="correlationId")
    domain: Optional[StrictStr] = Field(default=None, description="The domain of the event.")
    title: Optional[StrictStr] = Field(default=None, description="The title of the event.")
    description: Optional[StrictStr] = Field(default=None, description="An explnatory of the event.")
    priority: Optional[StrictStr] = Field(default=None, description="A priority.")
    time_occurred: Optional[datetime] = Field(default=None, description="The time the event occurred.", alias="timeOccurred")
    source: Optional[EntityRef] = None
    reporting_system: Optional[EntityRef] = Field(default=None, alias="reportingSystem")
    related_party: Optional[List[RelatedPartyRefOrPartyRoleRef]] = Field(default=None, alias="relatedParty")
    analytic_characteristic: Optional[List[Characteristic]] = Field(default=None, alias="analyticCharacteristic")
    event_id: Optional[StrictStr] = Field(default=None, description="The identifier of the notification.", alias="eventId")
    event_time: Optional[datetime] = Field(default=None, description="Time of the event occurrence.", alias="eventTime")
    event_type: Optional[StrictStr] = Field(default=None, description="The type of the notification.", alias="eventType")
    event: Optional[Dict[str, Any]] = Field(default=None, description="The event linked to the involved resource object")
    __properties: ClassVar[List[str]] = ["@type", "@baseType", "@schemaLocation", "href", "id", "correlationId", "domain", "title", "description", "priority", "timeOccurred", "source", "reportingSystem", "relatedParty", "analyticCharacteristic", "eventId", "eventTime", "eventType", "event"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Event from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of source
        if self.source:
            _dict['source'] = self.source.to_dict()
        # override the default output from pydantic by calling `to_dict()` of reporting_system
        if self.reporting_system:
            _dict['reportingSystem'] = self.reporting_system.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in related_party (list)
        _items = []
        if self.related_party:
            for _item in self.related_party:
                if _item:
                    _items.append(_item.to_dict())
            _dict['relatedParty'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in analytic_characteristic (list)
        _items = []
        if self.analytic_characteristic:
            for _item in self.analytic_characteristic:
                if _item:
                    _items.append(_item.to_dict())
            _dict['analyticCharacteristic'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of Event from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "@type": obj.get("@type"),
            "@baseType": obj.get("@baseType"),
            "@schemaLocation": obj.get("@schemaLocation"),
            "href": obj.get("href"),
            "id": obj.get("id"),
            "correlationId": obj.get("correlationId"),
            "domain": obj.get("domain"),
            "title": obj.get("title"),
            "description": obj.get("description"),
            "priority": obj.get("priority"),
            "timeOccurred": obj.get("timeOccurred"),
            "source": EntityRef.from_dict(obj.get("source")) if obj.get("source") is not None else None,
            "reportingSystem": EntityRef.from_dict(obj.get("reportingSystem")) if obj.get("reportingSystem") is not None else None,
            "relatedParty": [RelatedPartyRefOrPartyRoleRef.from_dict(_item) for _item in obj.get("relatedParty")] if obj.get("relatedParty") is not None else None,
            "analyticCharacteristic": [Characteristic.from_dict(_item) for _item in obj.get("analyticCharacteristic")] if obj.get("analyticCharacteristic") is not None else None,
            "eventId": obj.get("eventId"),
            "eventTime": obj.get("eventTime"),
            "eventType": obj.get("eventType"),
            "event": obj.get("event")
        })
        return _obj


