# coding: utf-8

"""
    Service Inventory Management

    The intent of this API is to provide a consistent/standardized mechanism to query and manipulate the Service inventory. The Service Inventory API can be used to query the service instances for a customer via Self Service Portal or the Call Centre operator can query the service instances on behalf of the customer while a customer may have a complaint or a query. Note: Only the CustomerFacingServices instances will be presented to the customer. The Service Inventory API can be called by the Service Order Management to create a new service instance/ update an existing service instance in the Service Inventory. ### Service resource Service is an abstract base class for defining the Service hierarchy. All Services are characterized as either being possibly visible and usable by a Customer or not. This gives rise to the two subclasses of  Service: CustomerFacingService and ResourceFacingService. ### Service Inventory API performs the following operations on service  : - Retrieve  a service or a collection of services depending on filter criteria - Partial update of a service (including updating rules) - Create a service (including default values and creation rules and for administration users only) - Delete a service (for administration users only) - Notification of events on service

    The version of the OpenAPI document: 5.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from importlib import import_module
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from openapi_server.models.characteristic_mvo import CharacteristicMVO
from openapi_server.models.constraint_ref_mvo import ConstraintRefMVO
from openapi_server.models.feature_relationship_mvo import FeatureRelationshipMVO
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class FeatureMVO(BaseModel):
    """
    FeatureMVO
    """ # noqa: E501
    type: StrictStr = Field(description="When sub-classing, this defines the sub-class Extensible name", alias="@type")
    base_type: Optional[StrictStr] = Field(default=None, description="When sub-classing, this defines the super-class", alias="@baseType")
    schema_location: Optional[StrictStr] = Field(default=None, description="A URI to a JSON-Schema file that defines additional attributes and relationships", alias="@schemaLocation")
    is_bundle: Optional[StrictBool] = Field(default=None, description="True if this is a feature group. Default is false.", alias="isBundle")
    feature_relationship: Optional[List[FeatureRelationshipMVO]] = Field(default=None, alias="featureRelationship")
    feature_characteristic: Optional[List[CharacteristicMVO]] = Field(default=None, description="This is a list of Characteristics for a particular feature.", alias="featureCharacteristic")
    constraint: Optional[List[ConstraintRefMVO]] = Field(default=None, description="This is a list of feature constraints.")
    is_enabled: Optional[StrictBool] = Field(default=None, description="True if this feature is enabled. Default is true.", alias="isEnabled")
    id: Optional[StrictStr] = Field(default=None, description="unique identifier")
    name: Optional[StrictStr] = Field(default=None, description="This is the name for the feature.")
    __properties: ClassVar[List[str]] = ["@type", "@baseType", "@schemaLocation", "isBundle", "featureRelationship", "featureCharacteristic", "constraint", "isEnabled", "id", "name"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of FeatureMVO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in feature_relationship (list)
        _items = []
        if self.feature_relationship:
            for _item in self.feature_relationship:
                if _item:
                    _items.append(_item.to_dict())
            _dict['featureRelationship'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in feature_characteristic (list)
        _items = []
        if self.feature_characteristic:
            for _item in self.feature_characteristic:
                if _item:
                    _items.append(_item.to_dict())
            _dict['featureCharacteristic'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in constraint (list)
        _items = []
        if self.constraint:
            for _item in self.constraint:
                if _item:
                    _items.append(_item.to_dict())
            _dict['constraint'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of FeatureMVO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "@type": obj.get("@type"),
            "@baseType": obj.get("@baseType"),
            "@schemaLocation": obj.get("@schemaLocation"),
            "isBundle": obj.get("isBundle"),
            "featureRelationship": [FeatureRelationshipMVO.from_dict(_item) for _item in obj.get("featureRelationship")] if obj.get("featureRelationship") is not None else None,
            "featureCharacteristic": [CharacteristicMVO.from_dict(_item) for _item in obj.get("featureCharacteristic")] if obj.get("featureCharacteristic") is not None else None,
            "constraint": [ConstraintRefMVO.from_dict(_item) for _item in obj.get("constraint")] if obj.get("constraint") is not None else None,
            "isEnabled": obj.get("isEnabled"),
            "id": obj.get("id"),
            "name": obj.get("name")
        })
        return _obj


