# coding: utf-8

"""
    Service Inventory Management

    The intent of this API is to provide a consistent/standardized mechanism to query and manipulate the Service inventory. The Service Inventory API can be used to query the service instances for a customer via Self Service Portal or the Call Centre operator can query the service instances on behalf of the customer while a customer may have a complaint or a query. Note: Only the CustomerFacingServices instances will be presented to the customer. The Service Inventory API can be called by the Service Order Management to create a new service instance/ update an existing service instance in the Service Inventory. ### Service resource Service is an abstract base class for defining the Service hierarchy. All Services are characterized as either being possibly visible and usable by a Customer or not. This gives rise to the two subclasses of  Service: CustomerFacingService and ResourceFacingService. ### Service Inventory API performs the following operations on service  : - Retrieve  a service or a collection of services depending on filter criteria - Partial update of a service (including updating rules) - Create a service (including default values and creation rules and for administration users only) - Delete a service (for administration users only) - Notification of events on service

    The version of the OpenAPI document: 5.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.calendar_period_mvo import CalendarPeriodMVO
from openapi_server.models.external_identifier_mvo import ExternalIdentifierMVO
from openapi_server.models.geographic_site_relationship_mvo import GeographicSiteRelationshipMVO
from openapi_server.models.place_mvo import PlaceMVO
from openapi_server.models.related_party_or_party_role_mvo import RelatedPartyOrPartyRoleMVO
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class GeographicSiteMVO(PlaceMVO):
    """
    GeographicSiteMVO
    """ # noqa: E501
    type: StrictStr = Field(description="When sub-classing, this defines the sub-class Extensible name", alias="@type")
    base_type: Optional[StrictStr] = Field(default=None, description="When sub-classing, this defines the super-class", alias="@baseType")
    schema_location: Optional[StrictStr] = Field(default=None, description="A URI to a JSON-Schema file that defines additional attributes and relationships", alias="@schemaLocation")
    code: Optional[StrictStr] = Field(default=None, description="A code that may be used for some addressing schemes eg: [ANSI T1.253-1999]")
    creation_date: Optional[datetime] = Field(default=None, description="Date and time when the GeographicSite was created", alias="creationDate")
    description: Optional[StrictStr] = Field(default=None, description="Text describing additional information regarding the site")
    status: Optional[StrictStr] = Field(default=None, description="The condition of the GeographicSite, such as planned, underConstruction, cancelled, active, inactive, former")
    related_party: Optional[List[RelatedPartyOrPartyRoleMVO]] = Field(default=None, alias="relatedParty")
    external_identifier: Optional[List[ExternalIdentifierMVO]] = Field(default=None, alias="externalIdentifier")
    calendar: Optional[List[CalendarPeriodMVO]] = None
    place: Optional[List[PlaceRefOrValueMVO]] = None
    site_relationship: Optional[List[GeographicSiteRelationshipMVO]] = Field(default=None, alias="siteRelationship")
    __properties: ClassVar[List[str]] = ["@type", "@baseType", "@schemaLocation", "code", "creationDate", "description", "status", "relatedParty", "externalIdentifier", "calendar", "place", "siteRelationship"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of GeographicSiteMVO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in related_party (list)
        _items = []
        if self.related_party:
            for _item in self.related_party:
                if _item:
                    _items.append(_item.to_dict())
            _dict['relatedParty'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in external_identifier (list)
        _items = []
        if self.external_identifier:
            for _item in self.external_identifier:
                if _item:
                    _items.append(_item.to_dict())
            _dict['externalIdentifier'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in calendar (list)
        _items = []
        if self.calendar:
            for _item in self.calendar:
                if _item:
                    _items.append(_item.to_dict())
            _dict['calendar'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in place (list)
        _items = []
        if self.place:
            for _item in self.place:
                if _item:
                    _items.append(_item.to_dict())
            _dict['place'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in site_relationship (list)
        _items = []
        if self.site_relationship:
            for _item in self.site_relationship:
                if _item:
                    _items.append(_item.to_dict())
            _dict['siteRelationship'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of GeographicSiteMVO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "@type": obj.get("@type"),
            "@baseType": obj.get("@baseType"),
            "@schemaLocation": obj.get("@schemaLocation"),
            "code": obj.get("code"),
            "creationDate": obj.get("creationDate"),
            "description": obj.get("description"),
            "status": obj.get("status"),
            "relatedParty": [RelatedPartyOrPartyRoleMVO.from_dict(_item) for _item in obj.get("relatedParty")] if obj.get("relatedParty") is not None else None,
            "externalIdentifier": [ExternalIdentifierMVO.from_dict(_item) for _item in obj.get("externalIdentifier")] if obj.get("externalIdentifier") is not None else None,
            "calendar": [CalendarPeriodMVO.from_dict(_item) for _item in obj.get("calendar")] if obj.get("calendar") is not None else None,
            "place": [PlaceRefOrValueMVO.from_dict(_item) for _item in obj.get("place")] if obj.get("place") is not None else None,
            "siteRelationship": [GeographicSiteRelationshipMVO.from_dict(_item) for _item in obj.get("siteRelationship")] if obj.get("siteRelationship") is not None else None
        })
        return _obj

from openapi_server.models.place_ref_or_value_mvo import PlaceRefOrValueMVO
# TODO: Rewrite to not use raise_errors
GeographicSiteMVO.model_rebuild(raise_errors=False)

