# coding: utf-8

"""
    Service Inventory Management

    The intent of this API is to provide a consistent/standardized mechanism to query and manipulate the Service inventory. The Service Inventory API can be used to query the service instances for a customer via Self Service Portal or the Call Centre operator can query the service instances on behalf of the customer while a customer may have a complaint or a query. Note: Only the CustomerFacingServices instances will be presented to the customer. The Service Inventory API can be called by the Service Order Management to create a new service instance/ update an existing service instance in the Service Inventory. ### Service resource Service is an abstract base class for defining the Service hierarchy. All Services are characterized as either being possibly visible and usable by a Customer or not. This gives rise to the two subclasses of  Service: CustomerFacingService and ResourceFacingService. ### Service Inventory API performs the following operations on service  : - Retrieve  a service or a collection of services depending on filter criteria - Partial update of a service (including updating rules) - Create a service (including default values and creation rules and for administration users only) - Delete a service (for administration users only) - Notification of events on service

    The version of the OpenAPI document: 5.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from importlib import import_module
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from openapi_server.models.geographic_sub_address_unit import GeographicSubAddressUnit
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class GeographicSubAddress(BaseModel):
    """
    GeographicSubAddress
    """ # noqa: E501
    type: StrictStr = Field(description="When sub-classing, this defines the sub-class Extensible name", alias="@type")
    base_type: Optional[StrictStr] = Field(default=None, description="When sub-classing, this defines the super-class", alias="@baseType")
    schema_location: Optional[StrictStr] = Field(default=None, description="A URI to a JSON-Schema file that defines additional attributes and relationships", alias="@schemaLocation")
    href: Optional[StrictStr] = Field(default=None, description="Link to the subAddress")
    id: Optional[StrictStr] = Field(default=None, description="Unique Identifier of the subAddress")
    building_name: Optional[StrictStr] = Field(default=None, description="allows for buildings that have well-known names", alias="buildingName")
    level_number: Optional[StrictStr] = Field(default=None, description="used where a level type may be repeated e.g. BASEMENT 1, BASEMENT 2", alias="levelNumber")
    level_type: Optional[StrictStr] = Field(default=None, description="describes level types within a building", alias="levelType")
    name: Optional[StrictStr] = Field(default=None, description="Name of the subAddress to identify it with a meaningful identification")
    private_street_name: Optional[StrictStr] = Field(default=None, description="private streets internal to a property (e.g. a university) may have internal names that are not recorded by the land title office.", alias="privateStreetName")
    private_street_number: Optional[StrictStr] = Field(default=None, description="private streets numbers internal to a private street", alias="privateStreetNumber")
    sub_unit: Optional[List[GeographicSubAddressUnit]] = Field(default=None, description="Representation of a SubUnit. It is used for describing subunit within a subAddress e.g. BERTH, FLAT, PIER, SUITE, SHOP, TOWER, UNIT, WHARF.", alias="subUnit")
    sub_address_type: Optional[StrictStr] = Field(default=None, description="Type of subAddress : it can be a subunit or a private street", alias="subAddressType")
    __properties: ClassVar[List[str]] = ["@type", "@baseType", "@schemaLocation", "href", "id", "buildingName", "levelNumber", "levelType", "name", "privateStreetName", "privateStreetNumber", "subUnit", "subAddressType"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of GeographicSubAddress from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in sub_unit (list)
        _items = []
        if self.sub_unit:
            for _item in self.sub_unit:
                if _item:
                    _items.append(_item.to_dict())
            _dict['subUnit'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of GeographicSubAddress from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "@type": obj.get("@type"),
            "@baseType": obj.get("@baseType"),
            "@schemaLocation": obj.get("@schemaLocation"),
            "href": obj.get("href"),
            "id": obj.get("id"),
            "buildingName": obj.get("buildingName"),
            "levelNumber": obj.get("levelNumber"),
            "levelType": obj.get("levelType"),
            "name": obj.get("name"),
            "privateStreetName": obj.get("privateStreetName"),
            "privateStreetNumber": obj.get("privateStreetNumber"),
            "subUnit": [GeographicSubAddressUnit.from_dict(_item) for _item in obj.get("subUnit")] if obj.get("subUnit") is not None else None,
            "subAddressType": obj.get("subAddressType")
        })
        return _obj


