# coding: utf-8

"""
    Service Inventory Management

    The intent of this API is to provide a consistent/standardized mechanism to query and manipulate the Service inventory. The Service Inventory API can be used to query the service instances for a customer via Self Service Portal or the Call Centre operator can query the service instances on behalf of the customer while a customer may have a complaint or a query. Note: Only the CustomerFacingServices instances will be presented to the customer. The Service Inventory API can be called by the Service Order Management to create a new service instance/ update an existing service instance in the Service Inventory. ### Service resource Service is an abstract base class for defining the Service hierarchy. All Services are characterized as either being possibly visible and usable by a Customer or not. This gives rise to the two subclasses of  Service: CustomerFacingService and ResourceFacingService. ### Service Inventory API performs the following operations on service  : - Retrieve  a service or a collection of services depending on filter criteria - Partial update of a service (including updating rules) - Create a service (including default values and creation rules and for administration users only) - Delete a service (for administration users only) - Notification of events on service

    The version of the OpenAPI document: 5.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.external_identifier_fvo import ExternalIdentifierFVO
from openapi_server.models.geographic_location_ref_or_value_fvo import GeographicLocationRefOrValueFVO
from openapi_server.models.geographic_sub_address_fvo import GeographicSubAddressFVO
from openapi_server.models.place_fvo import PlaceFVO
from openapi_server.models.standard_identifier_fvo import StandardIdentifierFVO
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class GeographicAddressFVO(PlaceFVO):
    """
    GeographicAddressFVO
    """ # noqa: E501
    type: StrictStr = Field(description="When sub-classing, this defines the sub-class Extensible name", alias="@type")
    base_type: Optional[StrictStr] = Field(default=None, description="When sub-classing, this defines the super-class", alias="@baseType")
    schema_location: Optional[StrictStr] = Field(default=None, description="A URI to a JSON-Schema file that defines additional attributes and relationships", alias="@schemaLocation")
    id: Optional[StrictStr] = Field(default=None, description="unique identifier")
    city: Optional[StrictStr] = Field(default=None, description="City that the address is in")
    country: Optional[StrictStr] = Field(default=None, description="Country that the address is in")
    locality: Optional[StrictStr] = Field(default=None, description="An area of defined or undefined boundaries within a local authority or other legislatively defined area, usually rural or semi rural in nature. [ANZLIC-STREET], or a suburb, a bounded locality within a city, town or shire principally of urban character [ANZLICSTREET]")
    postcode: Optional[StrictStr] = Field(default=None, description="descriptor for a postal delivery area, used to speed and simplify the delivery of mail (also know as zipcode)")
    state_or_province: Optional[StrictStr] = Field(default=None, description="the State or Province that the address is in", alias="stateOrProvince")
    street_name: Optional[StrictStr] = Field(default=None, description="Name of the street or other street type", alias="streetName")
    street_nr: Optional[StrictStr] = Field(default=None, description="Number identifying a specific property on a public street. It may be combined with streetNrLast for ranged addresses", alias="streetNr")
    street_nr_last: Optional[StrictStr] = Field(default=None, description="Last number in a range of street numbers allocated to a property", alias="streetNrLast")
    street_nr_last_suffix: Optional[StrictStr] = Field(default=None, description="Last street number suffix for a ranged address", alias="streetNrLastSuffix")
    street_nr_suffix: Optional[StrictStr] = Field(default=None, description="the first street number suffix", alias="streetNrSuffix")
    street_suffix: Optional[StrictStr] = Field(default=None, description="A modifier denoting a relative direction", alias="streetSuffix")
    street_type: Optional[StrictStr] = Field(default=None, description="alley, avenue, boulevard, brae, crescent, drive, highway, lane, terrace, parade, place, tarn, way, wharf ", alias="streetType")
    country_code: Optional[List[StandardIdentifierFVO]] = Field(default=None, description="Country codes are short alphabetic or numeric geographical codes (geocodes) developed to represent countries and dependent areas, for use in data processing and communications. Several different systems have been developed to do this. The term country code frequently refers to ISO 3166-1 alpha-2 or international dialing codes, the E.164 country calling codes.", alias="countryCode")
    external_identifier: Optional[List[ExternalIdentifierFVO]] = Field(default=None, alias="externalIdentifier")
    geographic_location: Optional[GeographicLocationRefOrValueFVO] = Field(default=None, alias="geographicLocation")
    geographic_sub_address: Optional[List[GeographicSubAddressFVO]] = Field(default=None, alias="geographicSubAddress")
    geographic_address_type: Optional[StrictStr] = Field(default=None, description="Classification of the address, e.g., residential, industrial ", alias="geographicAddressType")
    __properties: ClassVar[List[str]] = ["@type", "@baseType", "@schemaLocation", "id", "city", "country", "locality", "postcode", "stateOrProvince", "streetName", "streetNr", "streetNrLast", "streetNrLastSuffix", "streetNrSuffix", "streetSuffix", "streetType", "countryCode", "externalIdentifier", "geographicLocation", "geographicSubAddress", "geographicAddressType"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of GeographicAddressFVO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in country_code (list)
        _items = []
        if self.country_code:
            for _item in self.country_code:
                if _item:
                    _items.append(_item.to_dict())
            _dict['countryCode'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in external_identifier (list)
        _items = []
        if self.external_identifier:
            for _item in self.external_identifier:
                if _item:
                    _items.append(_item.to_dict())
            _dict['externalIdentifier'] = _items
        # override the default output from pydantic by calling `to_dict()` of geographic_location
        if self.geographic_location:
            _dict['geographicLocation'] = self.geographic_location.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in geographic_sub_address (list)
        _items = []
        if self.geographic_sub_address:
            for _item in self.geographic_sub_address:
                if _item:
                    _items.append(_item.to_dict())
            _dict['geographicSubAddress'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of GeographicAddressFVO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "@type": obj.get("@type"),
            "@baseType": obj.get("@baseType"),
            "@schemaLocation": obj.get("@schemaLocation"),
            "id": obj.get("id"),
            "city": obj.get("city"),
            "country": obj.get("country"),
            "locality": obj.get("locality"),
            "postcode": obj.get("postcode"),
            "stateOrProvince": obj.get("stateOrProvince"),
            "streetName": obj.get("streetName"),
            "streetNr": obj.get("streetNr"),
            "streetNrLast": obj.get("streetNrLast"),
            "streetNrLastSuffix": obj.get("streetNrLastSuffix"),
            "streetNrSuffix": obj.get("streetNrSuffix"),
            "streetSuffix": obj.get("streetSuffix"),
            "streetType": obj.get("streetType"),
            "countryCode": [StandardIdentifierFVO.from_dict(_item) for _item in obj.get("countryCode")] if obj.get("countryCode") is not None else None,
            "externalIdentifier": [ExternalIdentifierFVO.from_dict(_item) for _item in obj.get("externalIdentifier")] if obj.get("externalIdentifier") is not None else None,
            "geographicLocation": GeographicLocationRefOrValueFVO.from_dict(obj.get("geographicLocation")) if obj.get("geographicLocation") is not None else None,
            "geographicSubAddress": [GeographicSubAddressFVO.from_dict(_item) for _item in obj.get("geographicSubAddress")] if obj.get("geographicSubAddress") is not None else None,
            "geographicAddressType": obj.get("geographicAddressType")
        })
        return _obj


