# coding: utf-8

"""
    Service Inventory Management

    The intent of this API is to provide a consistent/standardized mechanism to query and manipulate the Service inventory. The Service Inventory API can be used to query the service instances for a customer via Self Service Portal or the Call Centre operator can query the service instances on behalf of the customer while a customer may have a complaint or a query. Note: Only the CustomerFacingServices instances will be presented to the customer. The Service Inventory API can be called by the Service Order Management to create a new service instance/ update an existing service instance in the Service Inventory. ### Service resource Service is an abstract base class for defining the Service hierarchy. All Services are characterized as either being possibly visible and usable by a Customer or not. This gives rise to the two subclasses of  Service: CustomerFacingService and ResourceFacingService. ### Service Inventory API performs the following operations on service  : - Retrieve  a service or a collection of services depending on filter criteria - Partial update of a service (including updating rules) - Create a service (including default values and creation rules and for administration users only) - Delete a service (for administration users only) - Notification of events on service

    The version of the OpenAPI document: 5.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.characteristic_mvo import CharacteristicMVO
from openapi_server.models.contact_medium_mvo import ContactMediumMVO
from openapi_server.models.disability import Disability
from openapi_server.models.external_identifier_mvo import ExternalIdentifierMVO
from openapi_server.models.individual_identification_mvo import IndividualIdentificationMVO
from openapi_server.models.individual_state_type import IndividualStateType
from openapi_server.models.language_ability import LanguageAbility
from openapi_server.models.other_name_individual import OtherNameIndividual
from openapi_server.models.party_credit_profile_mvo import PartyCreditProfileMVO
from openapi_server.models.party_mvo import PartyMVO
from openapi_server.models.skill import Skill
from openapi_server.models.tax_exemption_certificate_mvo import TaxExemptionCertificateMVO
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class IndividualMVO(PartyMVO):
    """
    IndividualMVO
    """ # noqa: E501
    type: StrictStr = Field(description="When sub-classing, this defines the sub-class Extensible name", alias="@type")
    base_type: Optional[StrictStr] = Field(default=None, description="When sub-classing, this defines the super-class", alias="@baseType")
    schema_location: Optional[StrictStr] = Field(default=None, description="A URI to a JSON-Schema file that defines additional attributes and relationships", alias="@schemaLocation")
    external_reference: Optional[List[ExternalIdentifierMVO]] = Field(default=None, description="List of identifiers of the Party in an external system, for example when party information is imported from a commerce system", alias="externalReference")
    party_characteristic: Optional[List[CharacteristicMVO]] = Field(default=None, description="List of additional characteristics that a Party can take on.", alias="partyCharacteristic")
    tax_exemption_certificate: Optional[List[TaxExemptionCertificateMVO]] = Field(default=None, description="List of tax exemptions granted to the party. For example, a war veteran might have partial exemption from state tax and a full exemption from federal tax", alias="taxExemptionCertificate")
    credit_rating: Optional[List[PartyCreditProfileMVO]] = Field(default=None, description="List of credit profiles and scores for the party, typically received from an external credit broker", alias="creditRating")
    related_party: Optional[List[RelatedPartyOrPartyRoleMVO]] = Field(default=None, description="List of parties and/or party roles related to this party", alias="relatedParty")
    contact_medium: Optional[List[ContactMediumMVO]] = Field(default=None, description="List of means for contacting the party, e.g. mobile phone, email address", alias="contactMedium")
    gender: Optional[StrictStr] = Field(default=None, description="Gender")
    place_of_birth: Optional[StrictStr] = Field(default=None, description="Reference to the place where the individual was born", alias="placeOfBirth")
    country_of_birth: Optional[StrictStr] = Field(default=None, description="Country where the individual was born", alias="countryOfBirth")
    nationality: Optional[StrictStr] = Field(default=None, description="Nationality")
    marital_status: Optional[StrictStr] = Field(default=None, description="Marital status (married, divorced, widow ...)", alias="maritalStatus")
    birth_date: Optional[datetime] = Field(default=None, description="Birth date", alias="birthDate")
    death_date: Optional[datetime] = Field(default=None, description="Date of death", alias="deathDate")
    title: Optional[StrictStr] = Field(default=None, description="Useful for titles (aristocratic, social,...) Pr, Dr, Sir, ...")
    aristocratic_title: Optional[StrictStr] = Field(default=None, description="e.g. Baron, Graf, Earl", alias="aristocraticTitle")
    generation: Optional[StrictStr] = Field(default=None, description="e.g.. Sr, Jr, III (the third)")
    preferred_given_name: Optional[StrictStr] = Field(default=None, description="Contains the chosen name by which the individual prefers to be addressed. Note: This name may be a name other than a given name, such as a nickname", alias="preferredGivenName")
    family_name_prefix: Optional[StrictStr] = Field(default=None, description="Family name prefix", alias="familyNamePrefix")
    legal_name: Optional[StrictStr] = Field(default=None, description="Legal name or birth name (name one has for official purposes)", alias="legalName")
    middle_name: Optional[StrictStr] = Field(default=None, description="Middles name or initial", alias="middleName")
    name: Optional[StrictStr] = Field(default=None, description="Full name flatten (first, middle, and last names) - this is the name that is expected to be presented in reference data types such as PartyRef, RelatedParty, etc. that refer to Individual")
    formatted_name: Optional[StrictStr] = Field(default=None, description="A fully formatted name in one string with all of its pieces in their proper place and all of the necessary punctuation. Useful for specific contexts (Chinese, Japanese, Korean)", alias="formattedName")
    location: Optional[StrictStr] = Field(default=None, description="Temporary current location of the individual (may be used if the individual has approved its sharing)")
    status: Optional[IndividualStateType] = None
    other_name: Optional[List[OtherNameIndividual]] = Field(default=None, description="List of other names by which this individual is known", alias="otherName")
    individual_identification: Optional[List[IndividualIdentificationMVO]] = Field(default=None, description="List of official identifications issued to the individual, such as passport, driving licence, social security number", alias="individualIdentification")
    disability: Optional[List[Disability]] = Field(default=None, description="List of disabilities suffered by the individual")
    language_ability: Optional[List[LanguageAbility]] = Field(default=None, description="List of national languages known by the individual", alias="languageAbility")
    skill: Optional[List[Skill]] = Field(default=None, description="List of skills exhibited by the individual")
    family_name: Optional[StrictStr] = Field(default=None, description="Contains the non-chosen or inherited name. Also known as last name in the Western context", alias="familyName")
    given_name: Optional[StrictStr] = Field(default=None, description="First name of the individual", alias="givenName")
    __properties: ClassVar[List[str]] = ["@type", "@baseType", "@schemaLocation", "externalReference", "partyCharacteristic", "taxExemptionCertificate", "creditRating", "relatedParty", "contactMedium", "gender", "placeOfBirth", "countryOfBirth", "nationality", "maritalStatus", "birthDate", "deathDate", "title", "aristocraticTitle", "generation", "preferredGivenName", "familyNamePrefix", "legalName", "middleName", "name", "formattedName", "location", "status", "otherName", "individualIdentification", "disability", "languageAbility", "skill", "familyName", "givenName"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of IndividualMVO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in external_reference (list)
        _items = []
        if self.external_reference:
            for _item in self.external_reference:
                if _item:
                    _items.append(_item.to_dict())
            _dict['externalReference'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in party_characteristic (list)
        _items = []
        if self.party_characteristic:
            for _item in self.party_characteristic:
                if _item:
                    _items.append(_item.to_dict())
            _dict['partyCharacteristic'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in tax_exemption_certificate (list)
        _items = []
        if self.tax_exemption_certificate:
            for _item in self.tax_exemption_certificate:
                if _item:
                    _items.append(_item.to_dict())
            _dict['taxExemptionCertificate'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in credit_rating (list)
        _items = []
        if self.credit_rating:
            for _item in self.credit_rating:
                if _item:
                    _items.append(_item.to_dict())
            _dict['creditRating'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in related_party (list)
        _items = []
        if self.related_party:
            for _item in self.related_party:
                if _item:
                    _items.append(_item.to_dict())
            _dict['relatedParty'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in contact_medium (list)
        _items = []
        if self.contact_medium:
            for _item in self.contact_medium:
                if _item:
                    _items.append(_item.to_dict())
            _dict['contactMedium'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in other_name (list)
        _items = []
        if self.other_name:
            for _item in self.other_name:
                if _item:
                    _items.append(_item.to_dict())
            _dict['otherName'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in individual_identification (list)
        _items = []
        if self.individual_identification:
            for _item in self.individual_identification:
                if _item:
                    _items.append(_item.to_dict())
            _dict['individualIdentification'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in disability (list)
        _items = []
        if self.disability:
            for _item in self.disability:
                if _item:
                    _items.append(_item.to_dict())
            _dict['disability'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in language_ability (list)
        _items = []
        if self.language_ability:
            for _item in self.language_ability:
                if _item:
                    _items.append(_item.to_dict())
            _dict['languageAbility'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in skill (list)
        _items = []
        if self.skill:
            for _item in self.skill:
                if _item:
                    _items.append(_item.to_dict())
            _dict['skill'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of IndividualMVO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "@type": obj.get("@type"),
            "@baseType": obj.get("@baseType"),
            "@schemaLocation": obj.get("@schemaLocation"),
            "externalReference": [ExternalIdentifierMVO.from_dict(_item) for _item in obj.get("externalReference")] if obj.get("externalReference") is not None else None,
            "partyCharacteristic": [CharacteristicMVO.from_dict(_item) for _item in obj.get("partyCharacteristic")] if obj.get("partyCharacteristic") is not None else None,
            "taxExemptionCertificate": [TaxExemptionCertificateMVO.from_dict(_item) for _item in obj.get("taxExemptionCertificate")] if obj.get("taxExemptionCertificate") is not None else None,
            "creditRating": [PartyCreditProfileMVO.from_dict(_item) for _item in obj.get("creditRating")] if obj.get("creditRating") is not None else None,
            "relatedParty": [RelatedPartyOrPartyRoleMVO.from_dict(_item) for _item in obj.get("relatedParty")] if obj.get("relatedParty") is not None else None,
            "contactMedium": [ContactMediumMVO.from_dict(_item) for _item in obj.get("contactMedium")] if obj.get("contactMedium") is not None else None,
            "gender": obj.get("gender"),
            "placeOfBirth": obj.get("placeOfBirth"),
            "countryOfBirth": obj.get("countryOfBirth"),
            "nationality": obj.get("nationality"),
            "maritalStatus": obj.get("maritalStatus"),
            "birthDate": obj.get("birthDate"),
            "deathDate": obj.get("deathDate"),
            "title": obj.get("title"),
            "aristocraticTitle": obj.get("aristocraticTitle"),
            "generation": obj.get("generation"),
            "preferredGivenName": obj.get("preferredGivenName"),
            "familyNamePrefix": obj.get("familyNamePrefix"),
            "legalName": obj.get("legalName"),
            "middleName": obj.get("middleName"),
            "name": obj.get("name"),
            "formattedName": obj.get("formattedName"),
            "location": obj.get("location"),
            "status": obj.get("status"),
            "otherName": [OtherNameIndividual.from_dict(_item) for _item in obj.get("otherName")] if obj.get("otherName") is not None else None,
            "individualIdentification": [IndividualIdentificationMVO.from_dict(_item) for _item in obj.get("individualIdentification")] if obj.get("individualIdentification") is not None else None,
            "disability": [Disability.from_dict(_item) for _item in obj.get("disability")] if obj.get("disability") is not None else None,
            "languageAbility": [LanguageAbility.from_dict(_item) for _item in obj.get("languageAbility")] if obj.get("languageAbility") is not None else None,
            "skill": [Skill.from_dict(_item) for _item in obj.get("skill")] if obj.get("skill") is not None else None,
            "familyName": obj.get("familyName"),
            "givenName": obj.get("givenName")
        })
        return _obj

from openapi_server.models.related_party_or_party_role_mvo import RelatedPartyOrPartyRoleMVO
# TODO: Rewrite to not use raise_errors
IndividualMVO.model_rebuild(raise_errors=False)

