# coding: utf-8

"""
    Service Inventory Management

    The intent of this API is to provide a consistent/standardized mechanism to query and manipulate the Service inventory. The Service Inventory API can be used to query the service instances for a customer via Self Service Portal or the Call Centre operator can query the service instances on behalf of the customer while a customer may have a complaint or a query. Note: Only the CustomerFacingServices instances will be presented to the customer. The Service Inventory API can be called by the Service Order Management to create a new service instance/ update an existing service instance in the Service Inventory. ### Service resource Service is an abstract base class for defining the Service hierarchy. All Services are characterized as either being possibly visible and usable by a Customer or not. This gives rise to the two subclasses of  Service: CustomerFacingService and ResourceFacingService. ### Service Inventory API performs the following operations on service  : - Retrieve  a service or a collection of services depending on filter criteria - Partial update of a service (including updating rules) - Create a service (including default values and creation rules and for administration users only) - Delete a service (for administration users only) - Notification of events on service

    The version of the OpenAPI document: 5.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.characteristic import Characteristic
from openapi_server.models.characteristic_relationship import CharacteristicRelationship
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class IntegerCharacteristic(Characteristic):
    """
    IntegerCharacteristic
    """ # noqa: E501
    type: StrictStr = Field(description="When sub-classing, this defines the sub-class Extensible name", alias="@type")
    base_type: Optional[StrictStr] = Field(default=None, description="When sub-classing, this defines the super-class", alias="@baseType")
    schema_location: Optional[StrictStr] = Field(default=None, description="A URI to a JSON-Schema file that defines additional attributes and relationships", alias="@schemaLocation")
    id: Optional[StrictStr] = Field(default=None, description="Unique identifier of the characteristic")
    name: Optional[StrictStr] = Field(default=None, description="Name of the characteristic")
    value_type: Optional[StrictStr] = Field(default=None, description="Data type of the value of the characteristic", alias="valueType")
    characteristic_relationship: Optional[List[CharacteristicRelationship]] = Field(default=None, alias="characteristicRelationship")
    value: Optional[StrictInt] = Field(default=None, description="Value of the characteristic")
    __properties: ClassVar[List[str]] = ["@type", "@baseType", "@schemaLocation", "id", "name", "valueType", "characteristicRelationship", "value"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of IntegerCharacteristic from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in characteristic_relationship (list)
        _items = []
        if self.characteristic_relationship:
            for _item in self.characteristic_relationship:
                if _item:
                    _items.append(_item.to_dict())
            _dict['characteristicRelationship'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of IntegerCharacteristic from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "@type": obj.get("@type"),
            "@baseType": obj.get("@baseType"),
            "@schemaLocation": obj.get("@schemaLocation"),
            "id": obj.get("id"),
            "name": obj.get("name"),
            "valueType": obj.get("valueType"),
            "characteristicRelationship": [CharacteristicRelationship.from_dict(_item) for _item in obj.get("characteristicRelationship")] if obj.get("characteristicRelationship") is not None else None,
            "value": obj.get("value")
        })
        return _obj


