# coding: utf-8

"""
    Service Inventory Management

    The intent of this API is to provide a consistent/standardized mechanism to query and manipulate the Service inventory. The Service Inventory API can be used to query the service instances for a customer via Self Service Portal or the Call Centre operator can query the service instances on behalf of the customer while a customer may have a complaint or a query. Note: Only the CustomerFacingServices instances will be presented to the customer. The Service Inventory API can be called by the Service Order Management to create a new service instance/ update an existing service instance in the Service Inventory. ### Service resource Service is an abstract base class for defining the Service hierarchy. All Services are characterized as either being possibly visible and usable by a Customer or not. This gives rise to the two subclasses of  Service: CustomerFacingService and ResourceFacingService. ### Service Inventory API performs the following operations on service  : - Retrieve  a service or a collection of services depending on filter criteria - Partial update of a service (including updating rules) - Create a service (including default values and creation rules and for administration users only) - Delete a service (for administration users only) - Notification of events on service

    The version of the OpenAPI document: 5.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from importlib import import_module
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from openapi_server.models.attachment_ref_or_value_mvo import AttachmentRefOrValueMVO
from openapi_server.models.characteristic_mvo import CharacteristicMVO
from openapi_server.models.entity_ref import EntityRef
from openapi_server.models.entity_relationship_mvo import EntityRelationshipMVO
from openapi_server.models.expression_mvo import ExpressionMVO
from openapi_server.models.related_party_ref_or_party_role_ref_mvo import RelatedPartyRefOrPartyRoleRefMVO
from openapi_server.models.time_period import TimePeriod
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class IntentMVO(BaseModel):
    """
    IntentMVO
    """ # noqa: E501
    type: StrictStr = Field(description="When sub-classing, this defines the sub-class Extensible name", alias="@type")
    base_type: Optional[StrictStr] = Field(default=None, description="When sub-classing, this defines the super-class", alias="@baseType")
    schema_location: Optional[StrictStr] = Field(default=None, description="A URI to a JSON-Schema file that defines additional attributes and relationships", alias="@schemaLocation")
    description: Optional[StrictStr] = Field(default=None, description="The description of the intent.")
    valid_for: Optional[TimePeriod] = Field(default=None, alias="validFor")
    is_bundle: Optional[StrictBool] = Field(default=None, description="isBundle determines whether an intent represents a single intent (false), or a bundle of intents(true).", alias="isBundle")
    priority: Optional[StrictStr] = Field(default=None, description="Can be used by intent owner to prioritize intents in an intent management system")
    status_change_date: Optional[datetime] = Field(default=None, description="A date time( DateTime). The date that the entity status changed to the current one", alias="statusChangeDate")
    context: Optional[StrictStr] = Field(default=None, description="A string used to give a context to the intent")
    version: Optional[StrictStr] = Field(default=None, description="A field that identifies the specific version of an instance of an intent.")
    intent_specification: Optional[EntityRef] = Field(default=None, alias="intentSpecification")
    intent_relationship: Optional[List[EntityRelationshipMVO]] = Field(default=None, description="A list of intents related to this intent", alias="intentRelationship")
    characteristic: Optional[List[CharacteristicMVO]] = None
    related_party: Optional[List[RelatedPartyRefOrPartyRoleRefMVO]] = Field(default=None, alias="relatedParty")
    attachment: Optional[List[AttachmentRefOrValueMVO]] = Field(default=None, description="Attachments that may be of relevance to this intent, such as picture, document, media")
    name: Optional[StrictStr] = Field(default=None, description="The name of the intent.")
    expression: Optional[ExpressionMVO] = None
    creation_date: Optional[datetime] = Field(default=None, description="Date and time of the creation of this REST resource", alias="creationDate")
    last_update: Optional[datetime] = Field(default=None, description="Date and time of the last update of this REST resource", alias="lastUpdate")
    lifecycle_status: Optional[StrictStr] = Field(default=None, description="Used to indicate the current lifecycle status of this intent", alias="lifecycleStatus")
    __properties: ClassVar[List[str]] = ["@type", "@baseType", "@schemaLocation", "description", "validFor", "isBundle", "priority", "statusChangeDate", "context", "version", "intentSpecification", "intentRelationship", "characteristic", "relatedParty", "attachment", "name", "expression", "creationDate", "lastUpdate", "lifecycleStatus"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of IntentMVO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of valid_for
        if self.valid_for:
            _dict['validFor'] = self.valid_for.to_dict()
        # override the default output from pydantic by calling `to_dict()` of intent_specification
        if self.intent_specification:
            _dict['intentSpecification'] = self.intent_specification.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in intent_relationship (list)
        _items = []
        if self.intent_relationship:
            for _item in self.intent_relationship:
                if _item:
                    _items.append(_item.to_dict())
            _dict['intentRelationship'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in characteristic (list)
        _items = []
        if self.characteristic:
            for _item in self.characteristic:
                if _item:
                    _items.append(_item.to_dict())
            _dict['characteristic'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in related_party (list)
        _items = []
        if self.related_party:
            for _item in self.related_party:
                if _item:
                    _items.append(_item.to_dict())
            _dict['relatedParty'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in attachment (list)
        _items = []
        if self.attachment:
            for _item in self.attachment:
                if _item:
                    _items.append(_item.to_dict())
            _dict['attachment'] = _items
        # override the default output from pydantic by calling `to_dict()` of expression
        if self.expression:
            _dict['expression'] = self.expression.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of IntentMVO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "@type": obj.get("@type"),
            "@baseType": obj.get("@baseType"),
            "@schemaLocation": obj.get("@schemaLocation"),
            "description": obj.get("description"),
            "validFor": TimePeriod.from_dict(obj.get("validFor")) if obj.get("validFor") is not None else None,
            "isBundle": obj.get("isBundle"),
            "priority": obj.get("priority"),
            "statusChangeDate": obj.get("statusChangeDate"),
            "context": obj.get("context"),
            "version": obj.get("version"),
            "intentSpecification": EntityRef.from_dict(obj.get("intentSpecification")) if obj.get("intentSpecification") is not None else None,
            "intentRelationship": [EntityRelationshipMVO.from_dict(_item) for _item in obj.get("intentRelationship")] if obj.get("intentRelationship") is not None else None,
            "characteristic": [CharacteristicMVO.from_dict(_item) for _item in obj.get("characteristic")] if obj.get("characteristic") is not None else None,
            "relatedParty": [RelatedPartyRefOrPartyRoleRefMVO.from_dict(_item) for _item in obj.get("relatedParty")] if obj.get("relatedParty") is not None else None,
            "attachment": [AttachmentRefOrValueMVO.from_dict(_item) for _item in obj.get("attachment")] if obj.get("attachment") is not None else None,
            "name": obj.get("name"),
            "expression": ExpressionMVO.from_dict(obj.get("expression")) if obj.get("expression") is not None else None,
            "creationDate": obj.get("creationDate"),
            "lastUpdate": obj.get("lastUpdate"),
            "lifecycleStatus": obj.get("lifecycleStatus")
        })
        return _obj


