# coding: utf-8

"""
    Service Inventory Management

    The intent of this API is to provide a consistent/standardized mechanism to query and manipulate the Service inventory. The Service Inventory API can be used to query the service instances for a customer via Self Service Portal or the Call Centre operator can query the service instances on behalf of the customer while a customer may have a complaint or a query. Note: Only the CustomerFacingServices instances will be presented to the customer. The Service Inventory API can be called by the Service Order Management to create a new service instance/ update an existing service instance in the Service Inventory. ### Service resource Service is an abstract base class for defining the Service hierarchy. All Services are characterized as either being possibly visible and usable by a Customer or not. This gives rise to the two subclasses of  Service: CustomerFacingService and ResourceFacingService. ### Service Inventory API performs the following operations on service  : - Retrieve  a service or a collection of services depending on filter criteria - Partial update of a service (including updating rules) - Create a service (including default values and creation rules and for administration users only) - Delete a service (for administration users only) - Notification of events on service

    The version of the OpenAPI document: 5.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.time_period import TimePeriod
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class LanguageAbility(BaseModel):
    """
    Ability of an individual to understand or converse in a language.
    """ # noqa: E501
    language_code: Optional[StrictStr] = Field(default=None, description="Language code (RFC 5646)", alias="languageCode")
    language_name: Optional[StrictStr] = Field(default=None, description="Language name", alias="languageName")
    is_favourite_language: Optional[StrictBool] = Field(default=None, description="A “true” value specifies whether the language is considered by the individual as his favourite one", alias="isFavouriteLanguage")
    writing_proficiency: Optional[StrictStr] = Field(default=None, description="Writing proficiency evaluated for this language", alias="writingProficiency")
    reading_proficiency: Optional[StrictStr] = Field(default=None, description="Reading proficiency evaluated for this language", alias="readingProficiency")
    speaking_proficiency: Optional[StrictStr] = Field(default=None, description="Speaking proficiency evaluated for this language", alias="speakingProficiency")
    listening_proficiency: Optional[StrictStr] = Field(default=None, description="Listening proficiency evaluated for this language", alias="listeningProficiency")
    valid_for: Optional[TimePeriod] = Field(default=None, alias="validFor")
    __properties: ClassVar[List[str]] = ["languageCode", "languageName", "isFavouriteLanguage", "writingProficiency", "readingProficiency", "speakingProficiency", "listeningProficiency", "validFor"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of LanguageAbility from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of valid_for
        if self.valid_for:
            _dict['validFor'] = self.valid_for.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of LanguageAbility from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "languageCode": obj.get("languageCode"),
            "languageName": obj.get("languageName"),
            "isFavouriteLanguage": obj.get("isFavouriteLanguage"),
            "writingProficiency": obj.get("writingProficiency"),
            "readingProficiency": obj.get("readingProficiency"),
            "speakingProficiency": obj.get("speakingProficiency"),
            "listeningProficiency": obj.get("listeningProficiency"),
            "validFor": TimePeriod.from_dict(obj.get("validFor")) if obj.get("validFor") is not None else None
        })
        return _obj


