# coding: utf-8

"""
    Service Inventory Management

    The intent of this API is to provide a consistent/standardized mechanism to query and manipulate the Service inventory. The Service Inventory API can be used to query the service instances for a customer via Self Service Portal or the Call Centre operator can query the service instances on behalf of the customer while a customer may have a complaint or a query. Note: Only the CustomerFacingServices instances will be presented to the customer. The Service Inventory API can be called by the Service Order Management to create a new service instance/ update an existing service instance in the Service Inventory. ### Service resource Service is an abstract base class for defining the Service hierarchy. All Services are characterized as either being possibly visible and usable by a Customer or not. This gives rise to the two subclasses of  Service: CustomerFacingService and ResourceFacingService. ### Service Inventory API performs the following operations on service  : - Retrieve  a service or a collection of services depending on filter criteria - Partial update of a service (including updating rules) - Create a service (including default values and creation rules and for administration users only) - Delete a service (for administration users only) - Notification of events on service

    The version of the OpenAPI document: 5.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.characteristic_fvo import CharacteristicFVO
from openapi_server.models.contact_medium_fvo import ContactMediumFVO
from openapi_server.models.external_identifier_fvo import ExternalIdentifierFVO
from openapi_server.models.organization_child_relationship_fvo import OrganizationChildRelationshipFVO
from openapi_server.models.organization_identification_fvo import OrganizationIdentificationFVO
from openapi_server.models.organization_parent_relationship_fvo import OrganizationParentRelationshipFVO
from openapi_server.models.organization_state_type import OrganizationStateType
from openapi_server.models.other_name_organization_fvo import OtherNameOrganizationFVO
from openapi_server.models.party_credit_profile_fvo import PartyCreditProfileFVO
from openapi_server.models.party_fvo import PartyFVO
from openapi_server.models.tax_exemption_certificate_fvo import TaxExemptionCertificateFVO
from openapi_server.models.time_period import TimePeriod
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class OrganizationFVO(PartyFVO):
    """
    OrganizationFVO
    """ # noqa: E501
    type: StrictStr = Field(description="When sub-classing, this defines the sub-class Extensible name", alias="@type")
    base_type: Optional[StrictStr] = Field(default=None, description="When sub-classing, this defines the super-class", alias="@baseType")
    schema_location: Optional[StrictStr] = Field(default=None, description="A URI to a JSON-Schema file that defines additional attributes and relationships", alias="@schemaLocation")
    id: Optional[StrictStr] = Field(default=None, description="unique identifier")
    external_reference: Optional[List[ExternalIdentifierFVO]] = Field(default=None, description="List of identifiers of the Party in an external system, for example when party information is imported from a commerce system", alias="externalReference")
    party_characteristic: Optional[List[CharacteristicFVO]] = Field(default=None, description="List of additional characteristics that a Party can take on.", alias="partyCharacteristic")
    tax_exemption_certificate: Optional[List[TaxExemptionCertificateFVO]] = Field(default=None, description="List of tax exemptions granted to the party. For example, a war veteran might have partial exemption from state tax and a full exemption from federal tax", alias="taxExemptionCertificate")
    credit_rating: Optional[List[PartyCreditProfileFVO]] = Field(default=None, description="List of credit profiles and scores for the party, typically received from an external credit broker", alias="creditRating")
    related_party: Optional[List[RelatedPartyOrPartyRoleFVO]] = Field(default=None, description="List of parties and/or party roles related to this party", alias="relatedParty")
    contact_medium: Optional[List[ContactMediumFVO]] = Field(default=None, description="List of means for contacting the party, e.g. mobile phone, email address", alias="contactMedium")
    is_legal_entity: Optional[StrictBool] = Field(default=None, description="If value is true, the organization is a legal entity known by a national referential.", alias="isLegalEntity")
    is_head_office: Optional[StrictBool] = Field(default=None, description="If value is true, the organization is the head office", alias="isHeadOffice")
    organization_type: Optional[StrictStr] = Field(default=None, description="Type of Organization (company, department...)", alias="organizationType")
    exists_during: Optional[TimePeriod] = Field(default=None, alias="existsDuring")
    name: Optional[StrictStr] = Field(default=None, description="Organization name (department name for example)")
    name_type: Optional[StrictStr] = Field(default=None, description="Type of the name : Co, Inc, Ltd, etc.", alias="nameType")
    status: Optional[OrganizationStateType] = None
    other_name: Optional[List[OtherNameOrganizationFVO]] = Field(default=None, description="List of additional names by which the organization is known", alias="otherName")
    organization_identification: Optional[List[OrganizationIdentificationFVO]] = Field(default=None, description="List of official identifiers given to the organization, for example company number in the registry of companies", alias="organizationIdentification")
    organization_child_relationship: Optional[List[OrganizationChildRelationshipFVO]] = Field(default=None, description="List of organizations that are contained within this organization. For example if this organization is the Legal Department, the child organizations might include Claims, Courts, Contracts", alias="organizationChildRelationship")
    organization_parent_relationship: Optional[OrganizationParentRelationshipFVO] = Field(default=None, alias="organizationParentRelationship")
    trading_name: Optional[StrictStr] = Field(default=None, description="Name that the organization (unit) trades under", alias="tradingName")
    __properties: ClassVar[List[str]] = ["@type", "@baseType", "@schemaLocation", "id", "externalReference", "partyCharacteristic", "taxExemptionCertificate", "creditRating", "relatedParty", "contactMedium", "isLegalEntity", "isHeadOffice", "organizationType", "existsDuring", "name", "nameType", "status", "otherName", "organizationIdentification", "organizationChildRelationship", "organizationParentRelationship", "tradingName"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of OrganizationFVO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in external_reference (list)
        _items = []
        if self.external_reference:
            for _item in self.external_reference:
                if _item:
                    _items.append(_item.to_dict())
            _dict['externalReference'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in party_characteristic (list)
        _items = []
        if self.party_characteristic:
            for _item in self.party_characteristic:
                if _item:
                    _items.append(_item.to_dict())
            _dict['partyCharacteristic'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in tax_exemption_certificate (list)
        _items = []
        if self.tax_exemption_certificate:
            for _item in self.tax_exemption_certificate:
                if _item:
                    _items.append(_item.to_dict())
            _dict['taxExemptionCertificate'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in credit_rating (list)
        _items = []
        if self.credit_rating:
            for _item in self.credit_rating:
                if _item:
                    _items.append(_item.to_dict())
            _dict['creditRating'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in related_party (list)
        _items = []
        if self.related_party:
            for _item in self.related_party:
                if _item:
                    _items.append(_item.to_dict())
            _dict['relatedParty'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in contact_medium (list)
        _items = []
        if self.contact_medium:
            for _item in self.contact_medium:
                if _item:
                    _items.append(_item.to_dict())
            _dict['contactMedium'] = _items
        # override the default output from pydantic by calling `to_dict()` of exists_during
        if self.exists_during:
            _dict['existsDuring'] = self.exists_during.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in other_name (list)
        _items = []
        if self.other_name:
            for _item in self.other_name:
                if _item:
                    _items.append(_item.to_dict())
            _dict['otherName'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in organization_identification (list)
        _items = []
        if self.organization_identification:
            for _item in self.organization_identification:
                if _item:
                    _items.append(_item.to_dict())
            _dict['organizationIdentification'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in organization_child_relationship (list)
        _items = []
        if self.organization_child_relationship:
            for _item in self.organization_child_relationship:
                if _item:
                    _items.append(_item.to_dict())
            _dict['organizationChildRelationship'] = _items
        # override the default output from pydantic by calling `to_dict()` of organization_parent_relationship
        if self.organization_parent_relationship:
            _dict['organizationParentRelationship'] = self.organization_parent_relationship.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of OrganizationFVO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "@type": obj.get("@type"),
            "@baseType": obj.get("@baseType"),
            "@schemaLocation": obj.get("@schemaLocation"),
            "id": obj.get("id"),
            "externalReference": [ExternalIdentifierFVO.from_dict(_item) for _item in obj.get("externalReference")] if obj.get("externalReference") is not None else None,
            "partyCharacteristic": [CharacteristicFVO.from_dict(_item) for _item in obj.get("partyCharacteristic")] if obj.get("partyCharacteristic") is not None else None,
            "taxExemptionCertificate": [TaxExemptionCertificateFVO.from_dict(_item) for _item in obj.get("taxExemptionCertificate")] if obj.get("taxExemptionCertificate") is not None else None,
            "creditRating": [PartyCreditProfileFVO.from_dict(_item) for _item in obj.get("creditRating")] if obj.get("creditRating") is not None else None,
            "relatedParty": [RelatedPartyOrPartyRoleFVO.from_dict(_item) for _item in obj.get("relatedParty")] if obj.get("relatedParty") is not None else None,
            "contactMedium": [ContactMediumFVO.from_dict(_item) for _item in obj.get("contactMedium")] if obj.get("contactMedium") is not None else None,
            "isLegalEntity": obj.get("isLegalEntity"),
            "isHeadOffice": obj.get("isHeadOffice"),
            "organizationType": obj.get("organizationType"),
            "existsDuring": TimePeriod.from_dict(obj.get("existsDuring")) if obj.get("existsDuring") is not None else None,
            "name": obj.get("name"),
            "nameType": obj.get("nameType"),
            "status": obj.get("status"),
            "otherName": [OtherNameOrganizationFVO.from_dict(_item) for _item in obj.get("otherName")] if obj.get("otherName") is not None else None,
            "organizationIdentification": [OrganizationIdentificationFVO.from_dict(_item) for _item in obj.get("organizationIdentification")] if obj.get("organizationIdentification") is not None else None,
            "organizationChildRelationship": [OrganizationChildRelationshipFVO.from_dict(_item) for _item in obj.get("organizationChildRelationship")] if obj.get("organizationChildRelationship") is not None else None,
            "organizationParentRelationship": OrganizationParentRelationshipFVO.from_dict(obj.get("organizationParentRelationship")) if obj.get("organizationParentRelationship") is not None else None,
            "tradingName": obj.get("tradingName")
        })
        return _obj

from openapi_server.models.related_party_or_party_role_fvo import RelatedPartyOrPartyRoleFVO
# TODO: Rewrite to not use raise_errors
OrganizationFVO.model_rebuild(raise_errors=False)

