# coding: utf-8

"""
    Service Inventory Management

    The intent of this API is to provide a consistent/standardized mechanism to query and manipulate the Service inventory. The Service Inventory API can be used to query the service instances for a customer via Self Service Portal or the Call Centre operator can query the service instances on behalf of the customer while a customer may have a complaint or a query. Note: Only the CustomerFacingServices instances will be presented to the customer. The Service Inventory API can be called by the Service Order Management to create a new service instance/ update an existing service instance in the Service Inventory. ### Service resource Service is an abstract base class for defining the Service hierarchy. All Services are characterized as either being possibly visible and usable by a Customer or not. This gives rise to the two subclasses of  Service: CustomerFacingService and ResourceFacingService. ### Service Inventory API performs the following operations on service  : - Retrieve  a service or a collection of services depending on filter criteria - Partial update of a service (including updating rules) - Create a service (including default values and creation rules and for administration users only) - Delete a service (for administration users only) - Notification of events on service

    The version of the OpenAPI document: 5.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from importlib import import_module
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from openapi_server.models.account_ref import AccountRef
from openapi_server.models.agreement_ref import AgreementRef
from openapi_server.models.characteristic import Characteristic
from openapi_server.models.contact_medium import ContactMedium
from openapi_server.models.credit_profile import CreditProfile
from openapi_server.models.party_ref import PartyRef
from openapi_server.models.party_role_specification_ref import PartyRoleSpecificationRef
from openapi_server.models.payment_method_ref import PaymentMethodRef
from openapi_server.models.time_period import TimePeriod
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class PartyRole(BaseModel):
    """
    PartyRole
    """ # noqa: E501
    type: StrictStr = Field(description="When sub-classing, this defines the sub-class Extensible name", alias="@type")
    base_type: Optional[StrictStr] = Field(default=None, description="When sub-classing, this defines the super-class", alias="@baseType")
    schema_location: Optional[StrictStr] = Field(default=None, description="A URI to a JSON-Schema file that defines additional attributes and relationships", alias="@schemaLocation")
    href: Optional[StrictStr] = Field(default=None, description="Hyperlink reference")
    id: Optional[StrictStr] = Field(default=None, description="unique identifier")
    name: Optional[StrictStr] = Field(default=None, description="A word, term, or phrase by which the PartyRole is known and distinguished from other PartyRoles. It's the name of the PartyRole unique entity.")
    description: Optional[StrictStr] = Field(default=None, description="A description of the PartyRole.")
    role: Optional[StrictStr] = Field(default=None, description="Role played by the engagedParty in this context. As role is defined by partyRoleSpecification, this role attribute can be used to precise the role defined by partyRoleSpecification, or it can be used to define the role in case there is no partyRoleSpecification.")
    engaged_party: Optional[PartyRef] = Field(default=None, alias="engagedParty")
    party_role_specification: Optional[PartyRoleSpecificationRef] = Field(default=None, alias="partyRoleSpecification")
    characteristic: Optional[List[Characteristic]] = Field(default=None, description="Describes the characteristic of a party role.")
    account: Optional[List[AccountRef]] = None
    agreement: Optional[List[AgreementRef]] = None
    contact_medium: Optional[List[ContactMedium]] = Field(default=None, alias="contactMedium")
    payment_method: Optional[List[PaymentMethodRef]] = Field(default=None, alias="paymentMethod")
    credit_profile: Optional[List[CreditProfile]] = Field(default=None, alias="creditProfile")
    related_party: Optional[List[RelatedPartyOrPartyRole]] = Field(default=None, alias="relatedParty")
    status: Optional[StrictStr] = Field(default=None, description="Used to track the lifecycle status of the party role.")
    status_reason: Optional[StrictStr] = Field(default=None, description="A string providing an explanation on the value of the status lifecycle. For instance if the status is Rejected, statusReason will provide the reason for rejection.", alias="statusReason")
    valid_for: Optional[TimePeriod] = Field(default=None, alias="validFor")
    __properties: ClassVar[List[str]] = ["@type", "@baseType", "@schemaLocation", "href", "id", "name", "description", "role", "engagedParty", "partyRoleSpecification", "characteristic", "account", "agreement", "contactMedium", "paymentMethod", "creditProfile", "relatedParty", "status", "statusReason", "validFor"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    # JSON field name that stores the object type
    __discriminator_property_name: ClassVar[List[str]] = '@type'

    # discriminator mappings
    __discriminator_value_class_map: ClassVar[Dict[str, str]] = {
        'BusinessPartner': 'BusinessPartner','Consumer': 'Consumer','PartyRole': 'PartyRole','Producer': 'Producer','Supplier': 'Supplier'
    }

    @classmethod
    def get_discriminator_value(cls, obj: Dict) -> str:
        """Returns the discriminator value (object type) of the data"""
        discriminator_value = obj[cls.__discriminator_property_name]
        if discriminator_value:
            return cls.__discriminator_value_class_map.get(discriminator_value)
        else:
            return None

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Union[Self, Self, Self, Self]:
        """Create an instance of PartyRole from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of engaged_party
        if self.engaged_party:
            _dict['engagedParty'] = self.engaged_party.to_dict()
        # override the default output from pydantic by calling `to_dict()` of party_role_specification
        if self.party_role_specification:
            _dict['partyRoleSpecification'] = self.party_role_specification.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in characteristic (list)
        _items = []
        if self.characteristic:
            for _item in self.characteristic:
                if _item:
                    _items.append(_item.to_dict())
            _dict['characteristic'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in account (list)
        _items = []
        if self.account:
            for _item in self.account:
                if _item:
                    _items.append(_item.to_dict())
            _dict['account'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in agreement (list)
        _items = []
        if self.agreement:
            for _item in self.agreement:
                if _item:
                    _items.append(_item.to_dict())
            _dict['agreement'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in contact_medium (list)
        _items = []
        if self.contact_medium:
            for _item in self.contact_medium:
                if _item:
                    _items.append(_item.to_dict())
            _dict['contactMedium'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in payment_method (list)
        _items = []
        if self.payment_method:
            for _item in self.payment_method:
                if _item:
                    _items.append(_item.to_dict())
            _dict['paymentMethod'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in credit_profile (list)
        _items = []
        if self.credit_profile:
            for _item in self.credit_profile:
                if _item:
                    _items.append(_item.to_dict())
            _dict['creditProfile'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in related_party (list)
        _items = []
        if self.related_party:
            for _item in self.related_party:
                if _item:
                    _items.append(_item.to_dict())
            _dict['relatedParty'] = _items
        # override the default output from pydantic by calling `to_dict()` of valid_for
        if self.valid_for:
            _dict['validFor'] = self.valid_for.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Union[Self, Self, Self, Self]:
        """Create an instance of PartyRole from a dict"""
        # look up the object type based on discriminator mapping
        object_type = cls.get_discriminator_value(obj)
        if object_type:
            klass = globals()[object_type]
            return klass.from_dict(obj)
        else:
            raise ValueError("PartyRole failed to lookup discriminator value from " +
                             json.dumps(obj) + ". Discriminator property name: " + cls.__discriminator_property_name +
                             ", mapping: " + json.dumps(cls.__discriminator_value_class_map))

from openapi_server.models.related_party_or_party_role import RelatedPartyOrPartyRole
# TODO: Rewrite to not use raise_errors
PartyRole.model_rebuild(raise_errors=False)

