# coding: utf-8

"""
    Service Inventory Management

    The intent of this API is to provide a consistent/standardized mechanism to query and manipulate the Service inventory. The Service Inventory API can be used to query the service instances for a customer via Self Service Portal or the Call Centre operator can query the service instances on behalf of the customer while a customer may have a complaint or a query. Note: Only the CustomerFacingServices instances will be presented to the customer. The Service Inventory API can be called by the Service Order Management to create a new service instance/ update an existing service instance in the Service Inventory. ### Service resource Service is an abstract base class for defining the Service hierarchy. All Services are characterized as either being possibly visible and usable by a Customer or not. This gives rise to the two subclasses of  Service: CustomerFacingService and ResourceFacingService. ### Service Inventory API performs the following operations on service  : - Retrieve  a service or a collection of services depending on filter criteria - Partial update of a service (including updating rules) - Create a service (including default values and creation rules and for administration users only) - Delete a service (for administration users only) - Notification of events on service

    The version of the OpenAPI document: 5.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401



from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from openapi_server.models.party_ref_fvo import PartyRefFVO
from openapi_server.models.party_role_ref_fvo import PartyRoleRefFVO
from typing import Union, Any, List, TYPE_CHECKING, Optional, Dict
from typing_extensions import Literal
from pydantic import StrictStr, Field
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

PARTYORPARTYROLEFVO_ONE_OF_SCHEMAS = ["BusinessPartnerFVO", "ConsumerFVO", "IndividualFVO", "OrganizationFVO", "PartyRefFVO", "PartyRoleFVO", "PartyRoleRefFVO", "ProducerFVO", "SupplierFVO"]

class PartyOrPartyRoleFVO(BaseModel):
    """
    
    """
    # data type: PartyRefFVO
    oneof_schema_1_validator: Optional[PartyRefFVO] = None
    # data type: PartyRoleRefFVO
    oneof_schema_2_validator: Optional[PartyRoleRefFVO] = None
    # data type: IndividualFVO
    oneof_schema_3_validator: Optional[IndividualFVO] = None
    # data type: OrganizationFVO
    oneof_schema_4_validator: Optional[OrganizationFVO] = None
    # data type: PartyRoleFVO
    oneof_schema_5_validator: Optional[PartyRoleFVO] = None
    # data type: SupplierFVO
    oneof_schema_6_validator: Optional[SupplierFVO] = None
    # data type: BusinessPartnerFVO
    oneof_schema_7_validator: Optional[BusinessPartnerFVO] = None
    # data type: ConsumerFVO
    oneof_schema_8_validator: Optional[ConsumerFVO] = None
    # data type: ProducerFVO
    oneof_schema_9_validator: Optional[ProducerFVO] = None
    actual_instance: Optional[Union[BusinessPartnerFVO, ConsumerFVO, IndividualFVO, OrganizationFVO, PartyRefFVO, PartyRoleFVO, PartyRoleRefFVO, ProducerFVO, SupplierFVO]] = None
    one_of_schemas: List[str] = Literal["BusinessPartnerFVO", "ConsumerFVO", "IndividualFVO", "OrganizationFVO", "PartyRefFVO", "PartyRoleFVO", "PartyRoleRefFVO", "ProducerFVO", "SupplierFVO"]

    model_config = {
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = PartyOrPartyRoleFVO.model_construct()
        error_messages = []
        match = 0
        # validate data type: PartyRefFVO
        if not isinstance(v, PartyRefFVO):
            error_messages.append(f"Error! Input type `{type(v)}` is not `PartyRefFVO`")
        else:
            match += 1
        # validate data type: PartyRoleRefFVO
        if not isinstance(v, PartyRoleRefFVO):
            error_messages.append(f"Error! Input type `{type(v)}` is not `PartyRoleRefFVO`")
        else:
            match += 1
        # validate data type: IndividualFVO
        if not isinstance(v, IndividualFVO):
            error_messages.append(f"Error! Input type `{type(v)}` is not `IndividualFVO`")
        else:
            match += 1
        # validate data type: OrganizationFVO
        if not isinstance(v, OrganizationFVO):
            error_messages.append(f"Error! Input type `{type(v)}` is not `OrganizationFVO`")
        else:
            match += 1
        # validate data type: PartyRoleFVO
        if not isinstance(v, PartyRoleFVO):
            error_messages.append(f"Error! Input type `{type(v)}` is not `PartyRoleFVO`")
        else:
            match += 1
        # validate data type: SupplierFVO
        if not isinstance(v, SupplierFVO):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SupplierFVO`")
        else:
            match += 1
        # validate data type: BusinessPartnerFVO
        if not isinstance(v, BusinessPartnerFVO):
            error_messages.append(f"Error! Input type `{type(v)}` is not `BusinessPartnerFVO`")
        else:
            match += 1
        # validate data type: ConsumerFVO
        if not isinstance(v, ConsumerFVO):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ConsumerFVO`")
        else:
            match += 1
        # validate data type: ProducerFVO
        if not isinstance(v, ProducerFVO):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ProducerFVO`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in PartyOrPartyRoleFVO with oneOf schemas: BusinessPartnerFVO, ConsumerFVO, IndividualFVO, OrganizationFVO, PartyRefFVO, PartyRoleFVO, PartyRoleRefFVO, ProducerFVO, SupplierFVO. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in PartyOrPartyRoleFVO with oneOf schemas: BusinessPartnerFVO, ConsumerFVO, IndividualFVO, OrganizationFVO, PartyRefFVO, PartyRoleFVO, PartyRoleRefFVO, ProducerFVO, SupplierFVO. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: dict) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into PartyRefFVO
        try:
            instance.actual_instance = PartyRefFVO.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into PartyRoleRefFVO
        try:
            instance.actual_instance = PartyRoleRefFVO.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into IndividualFVO
        try:
            instance.actual_instance = IndividualFVO.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into OrganizationFVO
        try:
            instance.actual_instance = OrganizationFVO.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into PartyRoleFVO
        try:
            instance.actual_instance = PartyRoleFVO.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into SupplierFVO
        try:
            instance.actual_instance = SupplierFVO.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into BusinessPartnerFVO
        try:
            instance.actual_instance = BusinessPartnerFVO.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ConsumerFVO
        try:
            instance.actual_instance = ConsumerFVO.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ProducerFVO
        try:
            instance.actual_instance = ProducerFVO.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into PartyOrPartyRoleFVO with oneOf schemas: BusinessPartnerFVO, ConsumerFVO, IndividualFVO, OrganizationFVO, PartyRefFVO, PartyRoleFVO, PartyRoleRefFVO, ProducerFVO, SupplierFVO. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into PartyOrPartyRoleFVO with oneOf schemas: BusinessPartnerFVO, ConsumerFVO, IndividualFVO, OrganizationFVO, PartyRefFVO, PartyRoleFVO, PartyRoleRefFVO, ProducerFVO, SupplierFVO. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        to_json = getattr(self.actual_instance, "to_json", None)
        if callable(to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Dict:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        to_dict = getattr(self.actual_instance, "to_dict", None)
        if callable(to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())

from openapi_server.models.business_partner_fvo import BusinessPartnerFVO
from openapi_server.models.consumer_fvo import ConsumerFVO
from openapi_server.models.individual_fvo import IndividualFVO
from openapi_server.models.organization_fvo import OrganizationFVO
from openapi_server.models.party_role_fvo import PartyRoleFVO
from openapi_server.models.producer_fvo import ProducerFVO
from openapi_server.models.supplier_fvo import SupplierFVO
# TODO: Rewrite to not use raise_errors
PartyOrPartyRoleFVO.model_rebuild(raise_errors=False)

