# coding: utf-8

"""
    Service Inventory Management

    The intent of this API is to provide a consistent/standardized mechanism to query and manipulate the Service inventory. The Service Inventory API can be used to query the service instances for a customer via Self Service Portal or the Call Centre operator can query the service instances on behalf of the customer while a customer may have a complaint or a query. Note: Only the CustomerFacingServices instances will be presented to the customer. The Service Inventory API can be called by the Service Order Management to create a new service instance/ update an existing service instance in the Service Inventory. ### Service resource Service is an abstract base class for defining the Service hierarchy. All Services are characterized as either being possibly visible and usable by a Customer or not. This gives rise to the two subclasses of  Service: CustomerFacingService and ResourceFacingService. ### Service Inventory API performs the following operations on service  : - Retrieve  a service or a collection of services depending on filter criteria - Partial update of a service (including updating rules) - Create a service (including default values and creation rules and for administration users only) - Delete a service (for administration users only) - Notification of events on service

    The version of the OpenAPI document: 5.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from importlib import import_module
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from openapi_server.models.characteristic_mvo import CharacteristicMVO
from openapi_server.models.contact_medium_mvo import ContactMediumMVO
from openapi_server.models.external_identifier_mvo import ExternalIdentifierMVO
from openapi_server.models.party_credit_profile_mvo import PartyCreditProfileMVO
from openapi_server.models.related_party_or_party_role_mvo import RelatedPartyOrPartyRoleMVO
from openapi_server.models.tax_exemption_certificate_mvo import TaxExemptionCertificateMVO
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class PartyMVO(BaseModel):
    """
    PartyMVO
    """ # noqa: E501
    type: StrictStr = Field(description="When sub-classing, this defines the sub-class Extensible name", alias="@type")
    base_type: Optional[StrictStr] = Field(default=None, description="When sub-classing, this defines the super-class", alias="@baseType")
    schema_location: Optional[StrictStr] = Field(default=None, description="A URI to a JSON-Schema file that defines additional attributes and relationships", alias="@schemaLocation")
    external_reference: Optional[List[ExternalIdentifierMVO]] = Field(default=None, description="List of identifiers of the Party in an external system, for example when party information is imported from a commerce system", alias="externalReference")
    party_characteristic: Optional[List[CharacteristicMVO]] = Field(default=None, description="List of additional characteristics that a Party can take on.", alias="partyCharacteristic")
    tax_exemption_certificate: Optional[List[TaxExemptionCertificateMVO]] = Field(default=None, description="List of tax exemptions granted to the party. For example, a war veteran might have partial exemption from state tax and a full exemption from federal tax", alias="taxExemptionCertificate")
    credit_rating: Optional[List[PartyCreditProfileMVO]] = Field(default=None, description="List of credit profiles and scores for the party, typically received from an external credit broker", alias="creditRating")
    related_party: Optional[List[RelatedPartyOrPartyRoleMVO]] = Field(default=None, description="List of parties and/or party roles related to this party", alias="relatedParty")
    contact_medium: Optional[List[ContactMediumMVO]] = Field(default=None, description="List of means for contacting the party, e.g. mobile phone, email address", alias="contactMedium")
    __properties: ClassVar[List[str]] = ["@type", "@baseType", "@schemaLocation", "externalReference", "partyCharacteristic", "taxExemptionCertificate", "creditRating", "relatedParty", "contactMedium"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    # JSON field name that stores the object type
    __discriminator_property_name: ClassVar[List[str]] = '@type'

    # discriminator mappings
    __discriminator_value_class_map: ClassVar[Dict[str, str]] = {
        'Individual': 'IndividualMVO','Organization': 'OrganizationMVO','Party': 'PartyMVO'
    }

    @classmethod
    def get_discriminator_value(cls, obj: Dict) -> str:
        """Returns the discriminator value (object type) of the data"""
        discriminator_value = obj[cls.__discriminator_property_name]
        if discriminator_value:
            return cls.__discriminator_value_class_map.get(discriminator_value)
        else:
            return None

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Union[Self, Self]:
        """Create an instance of PartyMVO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in external_reference (list)
        _items = []
        if self.external_reference:
            for _item in self.external_reference:
                if _item:
                    _items.append(_item.to_dict())
            _dict['externalReference'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in party_characteristic (list)
        _items = []
        if self.party_characteristic:
            for _item in self.party_characteristic:
                if _item:
                    _items.append(_item.to_dict())
            _dict['partyCharacteristic'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in tax_exemption_certificate (list)
        _items = []
        if self.tax_exemption_certificate:
            for _item in self.tax_exemption_certificate:
                if _item:
                    _items.append(_item.to_dict())
            _dict['taxExemptionCertificate'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in credit_rating (list)
        _items = []
        if self.credit_rating:
            for _item in self.credit_rating:
                if _item:
                    _items.append(_item.to_dict())
            _dict['creditRating'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in related_party (list)
        _items = []
        if self.related_party:
            for _item in self.related_party:
                if _item:
                    _items.append(_item.to_dict())
            _dict['relatedParty'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in contact_medium (list)
        _items = []
        if self.contact_medium:
            for _item in self.contact_medium:
                if _item:
                    _items.append(_item.to_dict())
            _dict['contactMedium'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Union[Self, Self]:
        """Create an instance of PartyMVO from a dict"""
        # look up the object type based on discriminator mapping
        object_type = cls.get_discriminator_value(obj)
        if object_type:
            klass = globals()[object_type]
            return klass.from_dict(obj)
        else:
            raise ValueError("PartyMVO failed to lookup discriminator value from " +
                             json.dumps(obj) + ". Discriminator property name: " + cls.__discriminator_property_name +
                             ", mapping: " + json.dumps(cls.__discriminator_value_class_map))


