# coding: utf-8

"""
    Service Inventory Management

    The intent of this API is to provide a consistent/standardized mechanism to query and manipulate the Service inventory. The Service Inventory API can be used to query the service instances for a customer via Self Service Portal or the Call Centre operator can query the service instances on behalf of the customer while a customer may have a complaint or a query. Note: Only the CustomerFacingServices instances will be presented to the customer. The Service Inventory API can be called by the Service Order Management to create a new service instance/ update an existing service instance in the Service Inventory. ### Service resource Service is an abstract base class for defining the Service hierarchy. All Services are characterized as either being possibly visible and usable by a Customer or not. This gives rise to the two subclasses of  Service: CustomerFacingService and ResourceFacingService. ### Service Inventory API performs the following operations on service  : - Retrieve  a service or a collection of services depending on filter criteria - Partial update of a service (including updating rules) - Create a service (including default values and creation rules and for administration users only) - Delete a service (for administration users only) - Notification of events on service

    The version of the OpenAPI document: 5.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401



from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from openapi_server.models.party_ref import PartyRef
from openapi_server.models.party_role_ref import PartyRoleRef
from typing import Union, Any, List, TYPE_CHECKING, Optional, Dict
from typing_extensions import Literal
from pydantic import StrictStr, Field
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

PARTYORPARTYROLE_ONE_OF_SCHEMAS = ["BusinessPartner", "Consumer", "Individual", "Organization", "PartyRef", "PartyRole", "PartyRoleRef", "Producer", "Supplier"]

class PartyOrPartyRole(BaseModel):
    """
    
    """
    # data type: PartyRef
    oneof_schema_1_validator: Optional[PartyRef] = None
    # data type: PartyRoleRef
    oneof_schema_2_validator: Optional[PartyRoleRef] = None
    # data type: Individual
    oneof_schema_3_validator: Optional[Individual] = None
    # data type: Organization
    oneof_schema_4_validator: Optional[Organization] = None
    # data type: PartyRole
    oneof_schema_5_validator: Optional[PartyRole] = None
    # data type: Supplier
    oneof_schema_6_validator: Optional[Supplier] = None
    # data type: BusinessPartner
    oneof_schema_7_validator: Optional[BusinessPartner] = None
    # data type: Consumer
    oneof_schema_8_validator: Optional[Consumer] = None
    # data type: Producer
    oneof_schema_9_validator: Optional[Producer] = None
    actual_instance: Optional[Union[BusinessPartner, Consumer, Individual, Organization, PartyRef, PartyRole, PartyRoleRef, Producer, Supplier]] = None
    one_of_schemas: List[str] = Literal["BusinessPartner", "Consumer", "Individual", "Organization", "PartyRef", "PartyRole", "PartyRoleRef", "Producer", "Supplier"]

    model_config = {
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = PartyOrPartyRole.model_construct()
        error_messages = []
        match = 0
        # validate data type: PartyRef
        if not isinstance(v, PartyRef):
            error_messages.append(f"Error! Input type `{type(v)}` is not `PartyRef`")
        else:
            match += 1
        # validate data type: PartyRoleRef
        if not isinstance(v, PartyRoleRef):
            error_messages.append(f"Error! Input type `{type(v)}` is not `PartyRoleRef`")
        else:
            match += 1
        # validate data type: Individual
        if not isinstance(v, Individual):
            error_messages.append(f"Error! Input type `{type(v)}` is not `Individual`")
        else:
            match += 1
        # validate data type: Organization
        if not isinstance(v, Organization):
            error_messages.append(f"Error! Input type `{type(v)}` is not `Organization`")
        else:
            match += 1
        # validate data type: PartyRole
        if not isinstance(v, PartyRole):
            error_messages.append(f"Error! Input type `{type(v)}` is not `PartyRole`")
        else:
            match += 1
        # validate data type: Supplier
        if not isinstance(v, Supplier):
            error_messages.append(f"Error! Input type `{type(v)}` is not `Supplier`")
        else:
            match += 1
        # validate data type: BusinessPartner
        if not isinstance(v, BusinessPartner):
            error_messages.append(f"Error! Input type `{type(v)}` is not `BusinessPartner`")
        else:
            match += 1
        # validate data type: Consumer
        if not isinstance(v, Consumer):
            error_messages.append(f"Error! Input type `{type(v)}` is not `Consumer`")
        else:
            match += 1
        # validate data type: Producer
        if not isinstance(v, Producer):
            error_messages.append(f"Error! Input type `{type(v)}` is not `Producer`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in PartyOrPartyRole with oneOf schemas: BusinessPartner, Consumer, Individual, Organization, PartyRef, PartyRole, PartyRoleRef, Producer, Supplier. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in PartyOrPartyRole with oneOf schemas: BusinessPartner, Consumer, Individual, Organization, PartyRef, PartyRole, PartyRoleRef, Producer, Supplier. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: dict) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into PartyRef
        try:
            instance.actual_instance = PartyRef.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into PartyRoleRef
        try:
            instance.actual_instance = PartyRoleRef.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into Individual
        try:
            instance.actual_instance = Individual.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into Organization
        try:
            instance.actual_instance = Organization.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into PartyRole
        try:
            instance.actual_instance = PartyRole.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into Supplier
        try:
            instance.actual_instance = Supplier.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into BusinessPartner
        try:
            instance.actual_instance = BusinessPartner.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into Consumer
        try:
            instance.actual_instance = Consumer.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into Producer
        try:
            instance.actual_instance = Producer.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into PartyOrPartyRole with oneOf schemas: BusinessPartner, Consumer, Individual, Organization, PartyRef, PartyRole, PartyRoleRef, Producer, Supplier. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into PartyOrPartyRole with oneOf schemas: BusinessPartner, Consumer, Individual, Organization, PartyRef, PartyRole, PartyRoleRef, Producer, Supplier. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        to_json = getattr(self.actual_instance, "to_json", None)
        if callable(to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Dict:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        to_dict = getattr(self.actual_instance, "to_dict", None)
        if callable(to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())

from openapi_server.models.business_partner import BusinessPartner
from openapi_server.models.consumer import Consumer
from openapi_server.models.individual import Individual
from openapi_server.models.organization import Organization
from openapi_server.models.party_role import PartyRole
from openapi_server.models.producer import Producer
from openapi_server.models.supplier import Supplier
# TODO: Rewrite to not use raise_errors
PartyOrPartyRole.model_rebuild(raise_errors=False)

