# coding: utf-8

"""
    Service Inventory Management

    The intent of this API is to provide a consistent/standardized mechanism to query and manipulate the Service inventory. The Service Inventory API can be used to query the service instances for a customer via Self Service Portal or the Call Centre operator can query the service instances on behalf of the customer while a customer may have a complaint or a query. Note: Only the CustomerFacingServices instances will be presented to the customer. The Service Inventory API can be called by the Service Order Management to create a new service instance/ update an existing service instance in the Service Inventory. ### Service resource Service is an abstract base class for defining the Service hierarchy. All Services are characterized as either being possibly visible and usable by a Customer or not. This gives rise to the two subclasses of  Service: CustomerFacingService and ResourceFacingService. ### Service Inventory API performs the following operations on service  : - Retrieve  a service or a collection of services depending on filter criteria - Partial update of a service (including updating rules) - Create a service (including default values and creation rules and for administration users only) - Delete a service (for administration users only) - Notification of events on service

    The version of the OpenAPI document: 5.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401



from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from openapi_server.models.party_ref_mvo import PartyRefMVO
from openapi_server.models.party_role_ref_mvo import PartyRoleRefMVO
from typing import Union, Any, List, TYPE_CHECKING, Optional, Dict
from typing_extensions import Literal
from pydantic import StrictStr, Field
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

PARTYORPARTYROLEMVO_ONE_OF_SCHEMAS = ["BusinessPartnerMVO", "ConsumerMVO", "IndividualMVO", "OrganizationMVO", "PartyRefMVO", "PartyRoleMVO", "PartyRoleRefMVO", "ProducerMVO", "SupplierMVO"]

class PartyOrPartyRoleMVO(BaseModel):
    """
    
    """
    # data type: PartyRefMVO
    oneof_schema_1_validator: Optional[PartyRefMVO] = None
    # data type: PartyRoleRefMVO
    oneof_schema_2_validator: Optional[PartyRoleRefMVO] = None
    # data type: IndividualMVO
    oneof_schema_3_validator: Optional[IndividualMVO] = None
    # data type: OrganizationMVO
    oneof_schema_4_validator: Optional[OrganizationMVO] = None
    # data type: PartyRoleMVO
    oneof_schema_5_validator: Optional[PartyRoleMVO] = None
    # data type: SupplierMVO
    oneof_schema_6_validator: Optional[SupplierMVO] = None
    # data type: BusinessPartnerMVO
    oneof_schema_7_validator: Optional[BusinessPartnerMVO] = None
    # data type: ConsumerMVO
    oneof_schema_8_validator: Optional[ConsumerMVO] = None
    # data type: ProducerMVO
    oneof_schema_9_validator: Optional[ProducerMVO] = None
    actual_instance: Optional[Union[BusinessPartnerMVO, ConsumerMVO, IndividualMVO, OrganizationMVO, PartyRefMVO, PartyRoleMVO, PartyRoleRefMVO, ProducerMVO, SupplierMVO]] = None
    one_of_schemas: List[str] = Literal["BusinessPartnerMVO", "ConsumerMVO", "IndividualMVO", "OrganizationMVO", "PartyRefMVO", "PartyRoleMVO", "PartyRoleRefMVO", "ProducerMVO", "SupplierMVO"]

    model_config = {
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = PartyOrPartyRoleMVO.model_construct()
        error_messages = []
        match = 0
        # validate data type: PartyRefMVO
        if not isinstance(v, PartyRefMVO):
            error_messages.append(f"Error! Input type `{type(v)}` is not `PartyRefMVO`")
        else:
            match += 1
        # validate data type: PartyRoleRefMVO
        if not isinstance(v, PartyRoleRefMVO):
            error_messages.append(f"Error! Input type `{type(v)}` is not `PartyRoleRefMVO`")
        else:
            match += 1
        # validate data type: IndividualMVO
        if not isinstance(v, IndividualMVO):
            error_messages.append(f"Error! Input type `{type(v)}` is not `IndividualMVO`")
        else:
            match += 1
        # validate data type: OrganizationMVO
        if not isinstance(v, OrganizationMVO):
            error_messages.append(f"Error! Input type `{type(v)}` is not `OrganizationMVO`")
        else:
            match += 1
        # validate data type: PartyRoleMVO
        if not isinstance(v, PartyRoleMVO):
            error_messages.append(f"Error! Input type `{type(v)}` is not `PartyRoleMVO`")
        else:
            match += 1
        # validate data type: SupplierMVO
        if not isinstance(v, SupplierMVO):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SupplierMVO`")
        else:
            match += 1
        # validate data type: BusinessPartnerMVO
        if not isinstance(v, BusinessPartnerMVO):
            error_messages.append(f"Error! Input type `{type(v)}` is not `BusinessPartnerMVO`")
        else:
            match += 1
        # validate data type: ConsumerMVO
        if not isinstance(v, ConsumerMVO):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ConsumerMVO`")
        else:
            match += 1
        # validate data type: ProducerMVO
        if not isinstance(v, ProducerMVO):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ProducerMVO`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in PartyOrPartyRoleMVO with oneOf schemas: BusinessPartnerMVO, ConsumerMVO, IndividualMVO, OrganizationMVO, PartyRefMVO, PartyRoleMVO, PartyRoleRefMVO, ProducerMVO, SupplierMVO. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in PartyOrPartyRoleMVO with oneOf schemas: BusinessPartnerMVO, ConsumerMVO, IndividualMVO, OrganizationMVO, PartyRefMVO, PartyRoleMVO, PartyRoleRefMVO, ProducerMVO, SupplierMVO. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: dict) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into PartyRefMVO
        try:
            instance.actual_instance = PartyRefMVO.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into PartyRoleRefMVO
        try:
            instance.actual_instance = PartyRoleRefMVO.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into IndividualMVO
        try:
            instance.actual_instance = IndividualMVO.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into OrganizationMVO
        try:
            instance.actual_instance = OrganizationMVO.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into PartyRoleMVO
        try:
            instance.actual_instance = PartyRoleMVO.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into SupplierMVO
        try:
            instance.actual_instance = SupplierMVO.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into BusinessPartnerMVO
        try:
            instance.actual_instance = BusinessPartnerMVO.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ConsumerMVO
        try:
            instance.actual_instance = ConsumerMVO.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ProducerMVO
        try:
            instance.actual_instance = ProducerMVO.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into PartyOrPartyRoleMVO with oneOf schemas: BusinessPartnerMVO, ConsumerMVO, IndividualMVO, OrganizationMVO, PartyRefMVO, PartyRoleMVO, PartyRoleRefMVO, ProducerMVO, SupplierMVO. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into PartyOrPartyRoleMVO with oneOf schemas: BusinessPartnerMVO, ConsumerMVO, IndividualMVO, OrganizationMVO, PartyRefMVO, PartyRoleMVO, PartyRoleRefMVO, ProducerMVO, SupplierMVO. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        to_json = getattr(self.actual_instance, "to_json", None)
        if callable(to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Dict:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        to_dict = getattr(self.actual_instance, "to_dict", None)
        if callable(to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())

from openapi_server.models.business_partner_mvo import BusinessPartnerMVO
from openapi_server.models.consumer_mvo import ConsumerMVO
from openapi_server.models.individual_mvo import IndividualMVO
from openapi_server.models.organization_mvo import OrganizationMVO
from openapi_server.models.party_role_mvo import PartyRoleMVO
from openapi_server.models.producer_mvo import ProducerMVO
from openapi_server.models.supplier_mvo import SupplierMVO
# TODO: Rewrite to not use raise_errors
PartyOrPartyRoleMVO.model_rebuild(raise_errors=False)

