# coding: utf-8

"""
    Service Inventory Management

    The intent of this API is to provide a consistent/standardized mechanism to query and manipulate the Service inventory. The Service Inventory API can be used to query the service instances for a customer via Self Service Portal or the Call Centre operator can query the service instances on behalf of the customer while a customer may have a complaint or a query. Note: Only the CustomerFacingServices instances will be presented to the customer. The Service Inventory API can be called by the Service Order Management to create a new service instance/ update an existing service instance in the Service Inventory. ### Service resource Service is an abstract base class for defining the Service hierarchy. All Services are characterized as either being possibly visible and usable by a Customer or not. This gives rise to the two subclasses of  Service: CustomerFacingService and ResourceFacingService. ### Service Inventory API performs the following operations on service  : - Retrieve  a service or a collection of services depending on filter criteria - Partial update of a service (including updating rules) - Create a service (including default values and creation rules and for administration users only) - Delete a service (for administration users only) - Notification of events on service

    The version of the OpenAPI document: 5.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class ServiceStateType(str, Enum):
    """
    Valid values for the lifecycle state of the service
    """

    """
    allowed enum values
    """
    FEASIBILITYCHECKED = 'feasibilityChecked'
    DESIGNED = 'designed'
    RESERVED = 'reserved'
    INACTIVE = 'inactive'
    ACTIVE = 'active'
    TERMINATED = 'terminated'
    SUSPENDED = 'suspended'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ServiceStateType from a JSON string"""
        return cls(json.loads(json_str))


