# coding: utf-8

"""
    Service Inventory Management

    The intent of this API is to provide a consistent/standardized mechanism to query and manipulate the Service inventory. The Service Inventory API can be used to query the service instances for a customer via Self Service Portal or the Call Centre operator can query the service instances on behalf of the customer while a customer may have a complaint or a query. Note: Only the CustomerFacingServices instances will be presented to the customer. The Service Inventory API can be called by the Service Order Management to create a new service instance/ update an existing service instance in the Service Inventory. ### Service resource Service is an abstract base class for defining the Service hierarchy. All Services are characterized as either being possibly visible and usable by a Customer or not. This gives rise to the two subclasses of  Service: CustomerFacingService and ResourceFacingService. ### Service Inventory API performs the following operations on service  : - Retrieve  a service or a collection of services depending on filter criteria - Partial update of a service (including updating rules) - Create a service (including default values and creation rules and for administration users only) - Delete a service (for administration users only) - Notification of events on service

    The version of the OpenAPI document: 5.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from importlib import import_module
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from openapi_server.models.characteristic import Characteristic
from openapi_server.models.external_identifier import ExternalIdentifier
from openapi_server.models.feature import Feature
from openapi_server.models.intent_ref_or_value import IntentRefOrValue
from openapi_server.models.note import Note
from openapi_server.models.related_entity_ref_or_value import RelatedEntityRefOrValue
from openapi_server.models.related_party_ref_or_party_role_ref import RelatedPartyRefOrPartyRoleRef
from openapi_server.models.related_place_ref_or_value import RelatedPlaceRefOrValue
from openapi_server.models.related_service_order_item import RelatedServiceOrderItem
from openapi_server.models.resource_ref import ResourceRef
from openapi_server.models.service_operating_status_type import ServiceOperatingStatusType
from openapi_server.models.service_specification_ref import ServiceSpecificationRef
from openapi_server.models.service_state_type import ServiceStateType
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class Service(BaseModel):
    """
    Service
    """ # noqa: E501
    type: StrictStr = Field(description="When sub-classing, this defines the sub-class Extensible name", alias="@type")
    base_type: Optional[StrictStr] = Field(default=None, description="When sub-classing, this defines the super-class", alias="@baseType")
    schema_location: Optional[StrictStr] = Field(default=None, description="A URI to a JSON-Schema file that defines additional attributes and relationships", alias="@schemaLocation")
    href: Optional[StrictStr] = Field(default=None, description="Hyperlink reference")
    id: Optional[StrictStr] = Field(default=None, description="unique identifier")
    description: Optional[StrictStr] = Field(default=None, description="Free-text description of the service")
    is_service_enabled: Optional[StrictBool] = Field(default=None, description="If FALSE and hasStarted is FALSE, this particular Service has NOT been enabled for use - if FALSE and hasStarted is TRUE then the service has failed ", alias="isServiceEnabled")
    has_started: Optional[StrictBool] = Field(default=None, description="If TRUE, this Service has already been started", alias="hasStarted")
    start_mode: Optional[StrictStr] = Field(default=None, description="This attribute is an enumerated integer that indicates how the Service is started, such as: 0: Unknown; 1: Automatically by the managed environment; 2: Automatically by the owning device; 3: Manually by the Provider of the Service; 4: Manually by a Customer of the Provider; 5: Any of the above", alias="startMode")
    is_stateful: Optional[StrictBool] = Field(default=None, description="If TRUE, this Service can be changed without affecting any other services", alias="isStateful")
    start_date: Optional[datetime] = Field(default=None, description="Date when the service starts", alias="startDate")
    end_date: Optional[datetime] = Field(default=None, description="Date when the service ends", alias="endDate")
    service_order_item: Optional[List[RelatedServiceOrderItem]] = Field(default=None, description="A list of service order items related to this service", alias="serviceOrderItem")
    note: Optional[List[Note]] = Field(default=None, description="A list of notes made on this service")
    service_type: Optional[StrictStr] = Field(default=None, description="Business type of the service", alias="serviceType")
    is_bundle: Optional[StrictBool] = Field(default=None, description="If true, the service is a ServiceBundle which regroup a service hierachy. If false, the service is a 'atomic' service (hierachy leaf).", alias="isBundle")
    name: Optional[StrictStr] = Field(default=None, description="Name of the service")
    category: Optional[StrictStr] = Field(default=None, description="Is it a customer facing or resource facing service")
    feature: Optional[List[Feature]] = Field(default=None, description="A list of feature associated with this service ")
    related_entity: Optional[List[RelatedEntityRefOrValue]] = Field(default=None, description="A list of related entities in relationship with this service", alias="relatedEntity")
    external_identifier: Optional[List[ExternalIdentifier]] = Field(default=None, description="A list of external identifiers assoicated with this service", alias="externalIdentifier")
    service_characteristic: Optional[List[Characteristic]] = Field(default=None, description="A list of characteristics that characterize this service (ServiceCharacteristic [*]) ", alias="serviceCharacteristic")
    service_relationship: Optional[List[ServiceRelationship]] = Field(default=None, description="A list of service relationships (ServiceRelationship [*]). Describes links with other service(s) in the inventory.", alias="serviceRelationship")
    supporting_service: Optional[List[ServiceRefOrValue]] = Field(default=None, description="A list of supporting services (SupportingService [*]). A collection of services that support this service (bundling, link CFS to RFS)", alias="supportingService")
    supporting_resource: Optional[List[ResourceRef]] = Field(default=None, description="A list of supporting resources (SupportingResource [*]).Note: only Service of type RFS can be associated with Resources", alias="supportingResource")
    related_party: Optional[List[RelatedPartyRefOrPartyRoleRef]] = Field(default=None, description="A list of related party references (RelatedParty [*]). A related party defines party or party role linked to a specific entity", alias="relatedParty")
    place: Optional[List[RelatedPlaceRefOrValue]] = Field(default=None, description="A list of places (Place [*]). Used to define a place useful for the service (for example a geographical place whre the service is installed)")
    state: Optional[StrictStr] = None
    operating_status: Optional[StrictStr] = Field(default=None, alias="operatingStatus")
    service_specification: Optional[ServiceSpecificationRef] = Field(default=None, alias="serviceSpecification")
    service_date: Optional[StrictStr] = Field(default=None, description="Date when the service was created (whatever its status).", alias="serviceDate")
    intent: Optional[IntentRefOrValue] = None
    __properties: ClassVar[List[str]] = ["@type", "@baseType", "@schemaLocation", "href", "id", "description", "isServiceEnabled", "hasStarted", "startMode", "isStateful", "startDate", "endDate", "serviceOrderItem", "note", "serviceType", "isBundle", "name", "category", "feature", "relatedEntity", "externalIdentifier", "serviceCharacteristic", "serviceRelationship", "supportingService", "supportingResource", "relatedParty", "place", "state", "operatingStatus", "serviceSpecification", "serviceDate", "intent"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Service from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in service_order_item (list)
        _items = []
        if self.service_order_item:
            for _item in self.service_order_item:
                if _item:
                    _items.append(_item.to_dict())
            _dict['serviceOrderItem'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in note (list)
        _items = []
        if self.note:
            for _item in self.note:
                if _item:
                    _items.append(_item.to_dict())
            _dict['note'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in feature (list)
        _items = []
        if self.feature:
            for _item in self.feature:
                if _item:
                    _items.append(_item.to_dict())
            _dict['feature'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in related_entity (list)
        _items = []
        if self.related_entity:
            for _item in self.related_entity:
                if _item:
                    _items.append(_item.to_dict())
            _dict['relatedEntity'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in external_identifier (list)
        _items = []
        if self.external_identifier:
            for _item in self.external_identifier:
                if _item:
                    _items.append(_item.to_dict())
            _dict['externalIdentifier'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in service_characteristic (list)
        _items = []
        if self.service_characteristic:
            for _item in self.service_characteristic:
                if _item:
                    _items.append(_item.to_dict())
            _dict['serviceCharacteristic'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in service_relationship (list)
        _items = []
        if self.service_relationship:
            for _item in self.service_relationship:
                if _item:
                    _items.append(_item.to_dict())
            _dict['serviceRelationship'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in supporting_service (list)
        _items = []
        if self.supporting_service:
            for _item in self.supporting_service:
                if _item:
                    _items.append(_item.to_dict())
            _dict['supportingService'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in supporting_resource (list)
        _items = []
        if self.supporting_resource:
            for _item in self.supporting_resource:
                if _item:
                    _items.append(_item.to_dict())
            _dict['supportingResource'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in related_party (list)
        _items = []
        if self.related_party:
            for _item in self.related_party:
                if _item:
                    _items.append(_item.to_dict())
            _dict['relatedParty'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in place (list)
        _items = []
        if self.place:
            for _item in self.place:
                if _item:
                    _items.append(_item.to_dict())
            _dict['place'] = _items
        # override the default output from pydantic by calling `to_dict()` of service_specification
        if self.service_specification:
            _dict['serviceSpecification'] = self.service_specification.to_dict()
        # override the default output from pydantic by calling `to_dict()` of intent
        if self.intent:
            _dict['intent'] = self.intent.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of Service from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "@type": obj.get("@type"),
            "@baseType": obj.get("@baseType"),
            "@schemaLocation": obj.get("@schemaLocation"),
            "href": obj.get("href"),
            "id": obj.get("id"),
            "description": obj.get("description"),
            "isServiceEnabled": obj.get("isServiceEnabled"),
            "hasStarted": obj.get("hasStarted"),
            "startMode": obj.get("startMode"),
            "isStateful": obj.get("isStateful"),
            "startDate": obj.get("startDate"),
            "endDate": obj.get("endDate"),
            "serviceOrderItem": [RelatedServiceOrderItem.from_dict(_item) for _item in obj.get("serviceOrderItem")] if obj.get("serviceOrderItem") is not None else None,
            "note": [Note.from_dict(_item) for _item in obj.get("note")] if obj.get("note") is not None else None,
            "serviceType": obj.get("serviceType"),
            "isBundle": obj.get("isBundle"),
            "name": obj.get("name"),
            "category": obj.get("category"),
            "feature": [Feature.from_dict(_item) for _item in obj.get("feature")] if obj.get("feature") is not None else None,
            "relatedEntity": [RelatedEntityRefOrValue.from_dict(_item) for _item in obj.get("relatedEntity")] if obj.get("relatedEntity") is not None else None,
            "externalIdentifier": [ExternalIdentifier.from_dict(_item) for _item in obj.get("externalIdentifier")] if obj.get("externalIdentifier") is not None else None,
            "serviceCharacteristic": [Characteristic.from_dict(_item) for _item in obj.get("serviceCharacteristic")] if obj.get("serviceCharacteristic") is not None else None,
            "serviceRelationship": [ServiceRelationship.from_dict(_item) for _item in obj.get("serviceRelationship")] if obj.get("serviceRelationship") is not None else None,
            "supportingService": [ServiceRefOrValue.from_dict(_item) for _item in obj.get("supportingService")] if obj.get("supportingService") is not None else None,
            "supportingResource": [ResourceRef.from_dict(_item) for _item in obj.get("supportingResource")] if obj.get("supportingResource") is not None else None,
            "relatedParty": [RelatedPartyRefOrPartyRoleRef.from_dict(_item) for _item in obj.get("relatedParty")] if obj.get("relatedParty") is not None else None,
            "place": [RelatedPlaceRefOrValue.from_dict(_item) for _item in obj.get("place")] if obj.get("place") is not None else None,
            "state": obj.get("state"),
            "operatingStatus": obj.get("operatingStatus"),
            "serviceSpecification": ServiceSpecificationRef.from_dict(obj.get("serviceSpecification")) if obj.get("serviceSpecification") is not None else None,
            "serviceDate": obj.get("serviceDate"),
            "intent": IntentRefOrValue.from_dict(obj.get("intent")) if obj.get("intent") is not None else None
        })
        return _obj

from openapi_server.models.service_ref_or_value import ServiceRefOrValue
from openapi_server.models.service_relationship import ServiceRelationship
# TODO: Rewrite to not use raise_errors
Service.model_rebuild(raise_errors=False)

