# coding: utf-8

"""
    Service Inventory Management

    The intent of this API is to provide a consistent/standardized mechanism to query and manipulate the Service inventory. The Service Inventory API can be used to query the service instances for a customer via Self Service Portal or the Call Centre operator can query the service instances on behalf of the customer while a customer may have a complaint or a query. Note: Only the CustomerFacingServices instances will be presented to the customer. The Service Inventory API can be called by the Service Order Management to create a new service instance/ update an existing service instance in the Service Inventory. ### Service resource Service is an abstract base class for defining the Service hierarchy. All Services are characterized as either being possibly visible and usable by a Customer or not. This gives rise to the two subclasses of  Service: CustomerFacingService and ResourceFacingService. ### Service Inventory API performs the following operations on service  : - Retrieve  a service or a collection of services depending on filter criteria - Partial update of a service (including updating rules) - Create a service (including default values and creation rules and for administration users only) - Delete a service (for administration users only) - Notification of events on service

    The version of the OpenAPI document: 5.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.account_ref_fvo import AccountRefFVO
from openapi_server.models.agreement_ref_fvo import AgreementRefFVO
from openapi_server.models.characteristic_fvo import CharacteristicFVO
from openapi_server.models.contact_medium_fvo import ContactMediumFVO
from openapi_server.models.credit_profile_fvo import CreditProfileFVO
from openapi_server.models.party_ref_fvo import PartyRefFVO
from openapi_server.models.party_role_fvo import PartyRoleFVO
from openapi_server.models.party_role_specification_ref_fvo import PartyRoleSpecificationRefFVO
from openapi_server.models.payment_method_ref_fvo import PaymentMethodRefFVO
from openapi_server.models.time_period import TimePeriod
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class SupplierFVO(PartyRoleFVO):
    """
    When business partner is the Supplier 
    """ # noqa: E501
    type: StrictStr = Field(description="When sub-classing, this defines the sub-class Extensible name", alias="@type")
    base_type: Optional[StrictStr] = Field(default=None, description="When sub-classing, this defines the super-class", alias="@baseType")
    schema_location: Optional[StrictStr] = Field(default=None, description="A URI to a JSON-Schema file that defines additional attributes and relationships", alias="@schemaLocation")
    id: Optional[StrictStr] = Field(default=None, description="unique identifier")
    name: StrictStr = Field(description="A word, term, or phrase by which the PartyRole is known and distinguished from other PartyRoles. It's the name of the PartyRole unique entity.")
    description: Optional[StrictStr] = Field(default=None, description="A description of the PartyRole.")
    role: Optional[StrictStr] = Field(default=None, description="Role played by the engagedParty in this context. As role is defined by partyRoleSpecification, this role attribute can be used to precise the role defined by partyRoleSpecification, or it can be used to define the role in case there is no partyRoleSpecification.")
    engaged_party: PartyRefFVO = Field(alias="engagedParty")
    party_role_specification: Optional[PartyRoleSpecificationRefFVO] = Field(default=None, alias="partyRoleSpecification")
    characteristic: Optional[List[CharacteristicFVO]] = Field(default=None, description="Describes the characteristic of a party role.")
    account: Optional[List[AccountRefFVO]] = None
    agreement: Optional[List[AgreementRefFVO]] = None
    contact_medium: Optional[List[ContactMediumFVO]] = Field(default=None, alias="contactMedium")
    payment_method: Optional[List[PaymentMethodRefFVO]] = Field(default=None, alias="paymentMethod")
    credit_profile: Optional[List[CreditProfileFVO]] = Field(default=None, alias="creditProfile")
    related_party: Optional[List[RelatedPartyOrPartyRoleFVO]] = Field(default=None, alias="relatedParty")
    status: Optional[StrictStr] = Field(default=None, description="Used to track the lifecycle status of the party role.")
    status_reason: Optional[StrictStr] = Field(default=None, description="A string providing an explanation on the value of the status lifecycle. For instance if the status is Rejected, statusReason will provide the reason for rejection.", alias="statusReason")
    valid_for: Optional[TimePeriod] = Field(default=None, alias="validFor")
    __properties: ClassVar[List[str]] = ["@type", "@baseType", "@schemaLocation", "id", "name", "description", "role", "engagedParty", "partyRoleSpecification", "characteristic", "account", "agreement", "contactMedium", "paymentMethod", "creditProfile", "relatedParty", "status", "statusReason", "validFor"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SupplierFVO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of engaged_party
        if self.engaged_party:
            _dict['engagedParty'] = self.engaged_party.to_dict()
        # override the default output from pydantic by calling `to_dict()` of party_role_specification
        if self.party_role_specification:
            _dict['partyRoleSpecification'] = self.party_role_specification.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in characteristic (list)
        _items = []
        if self.characteristic:
            for _item in self.characteristic:
                if _item:
                    _items.append(_item.to_dict())
            _dict['characteristic'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in account (list)
        _items = []
        if self.account:
            for _item in self.account:
                if _item:
                    _items.append(_item.to_dict())
            _dict['account'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in agreement (list)
        _items = []
        if self.agreement:
            for _item in self.agreement:
                if _item:
                    _items.append(_item.to_dict())
            _dict['agreement'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in contact_medium (list)
        _items = []
        if self.contact_medium:
            for _item in self.contact_medium:
                if _item:
                    _items.append(_item.to_dict())
            _dict['contactMedium'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in payment_method (list)
        _items = []
        if self.payment_method:
            for _item in self.payment_method:
                if _item:
                    _items.append(_item.to_dict())
            _dict['paymentMethod'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in credit_profile (list)
        _items = []
        if self.credit_profile:
            for _item in self.credit_profile:
                if _item:
                    _items.append(_item.to_dict())
            _dict['creditProfile'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in related_party (list)
        _items = []
        if self.related_party:
            for _item in self.related_party:
                if _item:
                    _items.append(_item.to_dict())
            _dict['relatedParty'] = _items
        # override the default output from pydantic by calling `to_dict()` of valid_for
        if self.valid_for:
            _dict['validFor'] = self.valid_for.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of SupplierFVO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "@type": obj.get("@type"),
            "@baseType": obj.get("@baseType"),
            "@schemaLocation": obj.get("@schemaLocation"),
            "id": obj.get("id"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "role": obj.get("role"),
            "engagedParty": PartyRefFVO.from_dict(obj.get("engagedParty")) if obj.get("engagedParty") is not None else None,
            "partyRoleSpecification": PartyRoleSpecificationRefFVO.from_dict(obj.get("partyRoleSpecification")) if obj.get("partyRoleSpecification") is not None else None,
            "characteristic": [CharacteristicFVO.from_dict(_item) for _item in obj.get("characteristic")] if obj.get("characteristic") is not None else None,
            "account": [AccountRefFVO.from_dict(_item) for _item in obj.get("account")] if obj.get("account") is not None else None,
            "agreement": [AgreementRefFVO.from_dict(_item) for _item in obj.get("agreement")] if obj.get("agreement") is not None else None,
            "contactMedium": [ContactMediumFVO.from_dict(_item) for _item in obj.get("contactMedium")] if obj.get("contactMedium") is not None else None,
            "paymentMethod": [PaymentMethodRefFVO.from_dict(_item) for _item in obj.get("paymentMethod")] if obj.get("paymentMethod") is not None else None,
            "creditProfile": [CreditProfileFVO.from_dict(_item) for _item in obj.get("creditProfile")] if obj.get("creditProfile") is not None else None,
            "relatedParty": [RelatedPartyOrPartyRoleFVO.from_dict(_item) for _item in obj.get("relatedParty")] if obj.get("relatedParty") is not None else None,
            "status": obj.get("status"),
            "statusReason": obj.get("statusReason"),
            "validFor": TimePeriod.from_dict(obj.get("validFor")) if obj.get("validFor") is not None else None
        })
        return _obj

from openapi_server.models.related_party_or_party_role_fvo import RelatedPartyOrPartyRoleFVO
# TODO: Rewrite to not use raise_errors
SupplierFVO.model_rebuild(raise_errors=False)

