# coding: utf-8

"""
    Service Inventory Management

    The intent of this API is to provide a consistent/standardized mechanism to query and manipulate the Service inventory. The Service Inventory API can be used to query the service instances for a customer via Self Service Portal or the Call Centre operator can query the service instances on behalf of the customer while a customer may have a complaint or a query. Note: Only the CustomerFacingServices instances will be presented to the customer. The Service Inventory API can be called by the Service Order Management to create a new service instance/ update an existing service instance in the Service Inventory. ### Service resource Service is an abstract base class for defining the Service hierarchy. All Services are characterized as either being possibly visible and usable by a Customer or not. This gives rise to the two subclasses of  Service: CustomerFacingService and ResourceFacingService. ### Service Inventory API performs the following operations on service  : - Retrieve  a service or a collection of services depending on filter criteria - Partial update of a service (including updating rules) - Create a service (including default values and creation rules and for administration users only) - Delete a service (for administration users only) - Notification of events on service

    The version of the OpenAPI document: 5.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from importlib import import_module
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from openapi_server.models.attachment_ref_or_value_mvo import AttachmentRefOrValueMVO
from openapi_server.models.tax_definition_mvo import TaxDefinitionMVO
from openapi_server.models.time_period import TimePeriod
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class TaxExemptionCertificateMVO(BaseModel):
    """
    TaxExemptionCertificateMVO
    """ # noqa: E501
    type: StrictStr = Field(description="When sub-classing, this defines the sub-class Extensible name", alias="@type")
    base_type: Optional[StrictStr] = Field(default=None, description="When sub-classing, this defines the super-class", alias="@baseType")
    schema_location: Optional[StrictStr] = Field(default=None, description="A URI to a JSON-Schema file that defines additional attributes and relationships", alias="@schemaLocation")
    id: Optional[StrictStr] = Field(default=None, description="Identifier of the tax exemption within list of the exemptions")
    tax_definition: Optional[List[TaxDefinitionMVO]] = Field(default=None, description="A list of taxes that are covered by the exemption, e.g. City Tax, State Tax. The definition would include the exemption (e.g. for a rate exemption 0% would be a full exemption, 5% could be a partial exemption if the actual rate was 10%).", alias="taxDefinition")
    valid_for: Optional[TimePeriod] = Field(default=None, alias="validFor")
    certificate_number: Optional[StrictStr] = Field(default=None, description="Identifier of a document that shows proof of exemption from taxes for the taxing jurisdiction", alias="certificateNumber")
    issuing_jurisdiction: Optional[StrictStr] = Field(default=None, description="Name of the jurisdiction that issued the exemption", alias="issuingJurisdiction")
    reason: Optional[StrictStr] = Field(default=None, description="Reason for the tax exemption")
    attachment: Optional[AttachmentRefOrValueMVO] = None
    __properties: ClassVar[List[str]] = ["@type", "@baseType", "@schemaLocation", "id", "taxDefinition", "validFor", "certificateNumber", "issuingJurisdiction", "reason", "attachment"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of TaxExemptionCertificateMVO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in tax_definition (list)
        _items = []
        if self.tax_definition:
            for _item in self.tax_definition:
                if _item:
                    _items.append(_item.to_dict())
            _dict['taxDefinition'] = _items
        # override the default output from pydantic by calling `to_dict()` of valid_for
        if self.valid_for:
            _dict['validFor'] = self.valid_for.to_dict()
        # override the default output from pydantic by calling `to_dict()` of attachment
        if self.attachment:
            _dict['attachment'] = self.attachment.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of TaxExemptionCertificateMVO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "@type": obj.get("@type"),
            "@baseType": obj.get("@baseType"),
            "@schemaLocation": obj.get("@schemaLocation"),
            "id": obj.get("id"),
            "taxDefinition": [TaxDefinitionMVO.from_dict(_item) for _item in obj.get("taxDefinition")] if obj.get("taxDefinition") is not None else None,
            "validFor": TimePeriod.from_dict(obj.get("validFor")) if obj.get("validFor") is not None else None,
            "certificateNumber": obj.get("certificateNumber"),
            "issuingJurisdiction": obj.get("issuingJurisdiction"),
            "reason": obj.get("reason"),
            "attachment": AttachmentRefOrValueMVO.from_dict(obj.get("attachment")) if obj.get("attachment") is not None else None
        })
        return _obj


